### ISSUE TITLE
Flash/AIR Application

### ISSUE THREAD

**Issue by twratl** [nebulous/infinitude#1]
This is in response to your question on whether or not the flash/air app can be controlled/scraped.

Not sure it is worth trying to scrape or control the app...BUT a little network traffic sniffing tells me the app is using oauth to authenticate and tools exist to extract data from SWF files. So you should be able to get the  consumer_key and consumer_secret from the flash file. Couple that with the login credentials and you _SHOULD_ be able to query the server by hacking together an oauth request based on the network traffic seen by the app.

**Comment by ohayon** [comment]
I know this issue is quite old, but I would also love to get my hands on this ruby code and the secret for an iOS app I am working on. 📱 Is there any chance you could forward those old emails?
