### ISSUE TITLE
Support for Centigrade (Sorry, duplicate) 

### ISSUE THREAD

**Issue by sarahmva** [nebulous/infinitude#104]
Our system is set to Centigrade, While the inside and set temperature are reported as centigrade with a "F" unit, the outside temperature is reported as real Fahrenheit. 

The system does send a variable `cfgem` that it is set to Centigrade or Fahrenheit.

![image](https://user-images.githubusercontent.com/68161487/87348008-0f088d00-c522-11ea-94a1-65441043daf1.png)

{"zone":[{"damperposition":["15"],"zoneconditioning":["active_cool"],"otmr":[{}],"rh":["40"],"name":["ZONE 1"],"fan":["off"],"rt":["26.0"],"hold":["off"],"id":"1","enabled":["on"],"clsp":["26.0"],"currentActivity":["home"],"htsp":["21.5"]},{"hold":["off"],"rt":[{}],"name":["Zone 2"],"fan":["off"],"enabled":["off"],"id":"2","currentActivity":["away"],"clsp":["26.5"],"htsp":["15.5"],"damperposition":["15"],"zoneconditioning":["active_cool"],"otmr":[{}],"rh":["40"]},{"zoneconditioning":["active_cool"],"damperposition":["15"],"rh":["40"],"otmr":[{}],"id":"3","enabled":["off"],"fan":["off"],"name":["Zone 3"],"rt":[{}],"hold":["off"],"htsp":["15.5"],"clsp":["26.5"],"currentActivity":["away"]},{"damperposition":["15"],"zoneconditioning":["active_cool"],"otmr":[{}],"rh":["40"],"fan":["off"],"name":["Zone 4"],"rt":[{}],"hold":["off"],"id":"4","enabled":["off"],"clsp":["26.5"],"currentActivity":["away"],"htsp":["15.5"]},{"hold":["off"],"rt":[{}],"fan":["off"],"name":["Zone 5"],"enabled":["off"],"id":"5","currentActivity":["away"],"clsp":["26.5"],"htsp":["15.5"],"damperposition":["15"],"zoneconditioning":["active_cool"],"otmr":[{}],"rh":["40"]},{"zoneconditioning":["active_cool"],"damperposition":["15"],"rh":["40"],"otmr":[{}],"enabled":["off"],"id":"6","hold":["off"],"rt":[{}],"fan":["off"],"name":["Zone 6"],"htsp":["15.5"],"currentActivity":["away"],"clsp":["26.5"]},{"htsp":["15.5"],"clsp":["26.5"],"currentActivity":["away"],"id":"7","enabled":["off"],"name":["Zone 7"],"fan":["off"],"rt":[{}],"hold":["off"],"rh":["40"],"otmr":[{}],"zoneconditioning":["active_cool"],"damperposition":["15"]},{"rh":["40"],"otmr":[{}],"zoneconditioning":["active_cool"],"damperposition":["15"],"htsp":["15.5"],"currentActivity":["away"],"clsp":["26.5"],"enabled":["off"],"id":"8","hold":["off"],"rt":[{}],"name":["Zone 8"],"fan":["off"]}]}

![image](https://user-images.githubusercontent.com/68161487/87348370-9a821e00-c522-11ea-83e6-3490d08a925f.png)

**Comment by nebulous** [comment]
Thanks for the additional detail. Linking Issue #82 here to keep track

**Comment by sarahmva** [comment]
Let me know if you need additional data capture. This is WIFI only, no serial.

**Comment by sarahmva** [comment]
Awesome! Thank you so much for the fix.
