### ISSUE TITLE
exec format error

### ISSUE THREAD

**Issue by Dalthar** [nebulous/infinitude#106]
I have Docker running on an Raspberry Pi 4, tried running the nebulous/infinitude:latest and every way I try I get

standard_init_linux.go:211: exec user process caused "exec format error"

**Comment by nebulous** [comment]
I think that's because the pi is an arm machine and the default build is Intel. Until I get automated multiple architecture builds setup, Scyto has a multiarch build at scyto/infinitude that will hopefully do the job.

**Comment by scyto** [comment]
yup my build should do the job just ```docker pull scyto\infinitude instead

**Comment by Dalthar** [comment]
That solved my problem. Still new to docker but should have thought of it being the wrong machine type. I don't need to use serial. Thank you both for the help.
