### ISSUE TITLE
serial over TCP-IP doesn

### ISSUE THREAD

**Issue by scyto** [nebulous/infinitude#107]

**Comment by scyto** [comment]
**expected behaviour**
when i power down the system, when it comes back up the serial page should reconnect over TCP/IP

**observed behaviour**
it doesn't

*repro steps*
get infinitude working and seeing serial data over TCP/IP
power down system for 1 minute
power it backup
wait for tstat to show connected to infinitude
look at serial tab to see if data is flowing

*notes*
this is for my modified container using debian, just incase thats the issue...

**Comment by HarrisonWilson** [comment]
I am having the same issue when using docker-compose. If I use "run" for the container, it passes in the SERIAL_SOCKET environment variable fine

**Comment by nebulous** [comment]
When you say "power down the system" do you mean the board running Infinitude, or the thermostat/airhandler?

**Comment by scyto** [comment]
Apologies should have been clearer.
I mean the main switch on the side of the hvac system - it turns off the SAM, the zone control, thermostat and   internal HVAC control board.

**Comment by nebulous** [comment]
If #107 didn't solve this problem we can reopen.
