### ISSUE TITLE
Initial Setup Assistance?

### ISSUE THREAD

**Issue by appleguru** [nebulous/infinitude#108]
Perhaps I'm missing something, but how do I actually control my thermostat via this interface? (For example, how can I adjust the set point and / or fan speed?)

I just got this setup on an RPI, this is what I see now:

<img width="916" alt="Screen Shot 2020-09-16 at 12 16 15 AM" src="https://user-images.githubusercontent.com/595829/93291734-ddc26c80-f7b1-11ea-8de2-d1363db07fbc.png">

Also, is infinitude.json documented somewhere? I currently have mine set to:

{"app_secret":"Pogotudinal","pass_reqs":15,"serial_socket":"127.0.0.1:23","serial_tty":""}

But this is completely a guess as I'm not really sure what is supposed to be set in there.

I do not have an RS485 interface currently. I have a Bryant branded SYSTXBBWEC01B controlling a Carrier Infinity system.

Thanks in advance for any help!

**Comment by appleguru** [comment]
Small update, seems I can change the settings via an api call, something like: http://192.168.1.175/api/1/activity/manual?htsp=72&fan=low

Is there not a way to control this via the built in web UI? Is that read only? Or?

**Comment by nebulous** [comment]
To change setpoints in the web interface, see the Comfort Profile tab. For example, in the screenshot below the stat is being put into manual mode at 69f at medium fan speed until 1:15pm. The api call also works, as you mentioned.

![image](https://user-images.githubusercontent.com/177510/93340138-6cf37280-f7fa-11ea-98f0-f3d605e34d9e.png)

**Comment by nebulous** [comment]
re configuration variables: I added a description column to the env var descriptions(which have lowercase analogs in infinitude.json) here https://github.com/nebulous/infinitude#docker

**Comment by adamurban** [comment]
Thanks. Is this polling the carrier servers for data or getting it locally from the thermostat? (What’s the impact of adjusting the pass_reqs variable?)

Also, is there any way to set the fan to a specific RPM? Something like what infinitive can do: https://github.com/acd/infinitive

**Comment by appleguru** [comment]
Thanks. Is this polling the carrier servers for data or getting it locally from the thermostat? (What’s the impact of adjusting the pass_reqs variable?)

Also, is there any way to set the fan to a specific RPM? Something like what infinitive can do: https://github.com/acd/infinitive

**Comment by Bit24888** [comment]
#``0x0a994b6c13e6a1df5a111d5a50b853212da57a1f

**Comment by adamurban** [comment]
Thanks, that diagram is *super* helpful. Should probably include it in the read me :-)

So setting pass_reqs to 0 is the correct way to disable talking to carrier's servers? Or?

Also, I thought I read somewhere that there was a bug /that using the native app + infinitude broke things and that it had to be one or the other?

**Comment by nebulous** [comment]
> So setting pass_reqs to 0 is the correct way to disable talking to carrier's servers? Or?

yep. And if you need to pass requests, try to set the timeout sufficiently long to be polite to Carrier's infrastructure.

> Also, I thought I read somewhere that there was a bug /that using the native app + infinitude broke things and that it had to be one or the other?

I don't believe that's the case at the present time, but if you discover a reproducible problem, feel free to file a bug, or better yet a patch!
