### ISSUE TITLE
request: selectable displays on status page?

### ISSUE THREAD

**Issue by scyto** [nebulous/infinitude#11]
I don't have outside, coil, airflow or blower speed (as the person who fitted the AC never ran a bus out to the AC) it would be great if could turn the display of these off and replace with zone data.  Is there an display control you could switch too that would allow adding / removing of each 'speedo control'?

**Comment by nebulous** [comment]
Changed some gauges to hide themselves if they don't have data. Does that satisfactorily cover this use case?

**Comment by nebulous** [comment]
Closing for now with the assumption auto-hiding makes sense. If not, reopen as needed.
