### ISSUE TITLE
Not getting any data from USB RS485

### ISSUE THREAD

**Issue by jkfromk** [nebulous/infinitude#115]
I am having trouble with getting infinitude with the USB RS485 working

**Symptom:**
- No data coming from RS485.

**Hardware:**
- Raspberry Pi Zero
- USB to RS485 Adapter. Wired A & B from Air Handler to A & B on the adapter.  I am using this adapter: 

https://smile.amazon.com/gp/product/B07SC2MJ91/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

**Steps I've done:**
- Followed install / config instructions from here:https://github.com/nebulous/infinitude/wiki/Installing-Infinitude-on-Raspberry-PI-(raspbian) I did not follow UART instructions other than running: stty < /dev/ttyUSB0 38400 -echo -opost -isig -icanon m
- Updated thermostat to proxy to infinitude on port 3000
- Ensured .json file has serial_tty  as /dev/ttyUSB0  It was already set this way so didn't have to change it.  I did notice serial_socket is set however not sure if that should be there. 
- Ensured the USB 485 adapter is seen:

	pi@raspberrypi:~/infinitude $ lsusb

	Bus 001 Device 003: ID 0403:6001 Future Technology Devices International, Ltd FT232 Serial (UART) IC
	Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

when infinitude is started:
	pi@raspberrypi:~/infinitude $ ./infinitude daemon -m production

	Using /dev/ttyUSB0 serial interface
	Using 127.0.0.1:23 for serial interface
	[2020-12-02 11:01:09.03549] [18367] [info] Listening at "http://*:3000"
	Server available at http://127.0.0.1:3000

Not sure what else to try to get it working.  Thank you in advance.

**Comment by nebulous** [comment]
Have you checked to see that serial data is arriving as expected without infinitude? Using minicom for instance? Or you could compile the `cardump` utility in the `contrib` directory for a standalone test. 

https://github.com/nebulous/infinitude/tree/master/contrib/cardump

Once that part is confirmed working(some people have had substantial trouble with wire gauge mismatches etc) we can troubleshoot the infinitude part of the pipeline, though there isn't really much to that bit. Just browse to the inifinitude homepage and click the Serial tab.

**Comment by jkfromk** [comment]
I compiled cardump and see data scrolling  when running ./cardump < /dev/ttyUSB0.  

Also seems the pi is seeing the USB device:

[87351.294711] usb 1-1: New USB device found, idVendor=0403, idProduct=6001, bcdDevice= 6.00
[87351.294735] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[87351.294749] usb 1-1: Product: FT232R USB UART
[87351.294762] usb 1-1: Manufacturer: FTDI
[87351.294775] usb 1-1: SerialNumber: AD0K19NV
[87351.311917] ftdi_sio 1-1:1.0: FTDI USB Serial Device converter detected
[87351.312171] usb 1-1: Detected FT232RL
[87351.314022] usb 1-1: FTDI USB Serial Device converter now attached to ttyUSB0

Is there something particular I should be looking for?  When I go to the serial tab I am not seeing any data under stream or state.

**Comment by nebulous** [comment]
`cardump` should show a stream of serial data, some of which is human readable. Did you see anything after the `[87351.314022] usb 1-1: FTDI USB Serial Device converter now attached to ttyUSB0` line?

**Comment by jkfromk** [comment]
When running "./cardump < /dev/ttyUSB0" 

I am seeing the following scroll by:

Looking for 8 byte frame in 140 byte buffer (The actual bye and buffer values change with each entry)

Side note:  I do see info in the other tabs (Status, Comfort, Schedules)

**Comment by nebulous** [comment]
if `cardump` doesn't sync and output a stream of actual data, some of which is ASCII text, then there remains an upstream problem from infinitude regarding serial data. I've heard some people have had trouble with using cat5 vs thicker thermostat wire, long runs may also be an issue. 485 is differential, but it may also help to make grounds common/try different adaptor/iterate.

However, you should know that the RS485 support in Infinitude is something of a novelty. It provides some insight into how the different devices on your bus are talking to each other, but is read-only from Infinitude's perspective.

**Comment by secabeen** [comment]
> However, you should know that the RS485 support in Infinitude is something of a novelty. It provides some insight into how the different devices on your bus are talking to each other, but is read-only from Infinitude's perspective.

It may be a novelty, but it's what dragged me into getting a home assistant setup going.  I have rs 485 sniffers/links to both my pool pump and my solar inverter, and love getting the data.

**Comment by nebulous** [comment]
😄  you’re exactly the target demographic then

**Comment by jlg89** [comment]
@jkfromk were you able to get your serial comms working? I'm running into the same issue. It's maybe a 40ft run of wire. I originally ran rather thin wiring, but just swapped it out for a 14ga pair. No change.

**Comment by jkfromk** [comment]
no afraid not. I used thermostat wire but only able 3 ft  of it.
