### ISSUE TITLE
Websocket opened, but no streaming source found

### ISSUE THREAD

**Issue by cfilkins** [nebulous/infinitude#116]
I just had a Heil Ion system installed, which is the same platform as the Carrier Infinity.  I have HomeAssistant, and am running Infinitude in a docker container.  In developer mode, I can see that data is being sent to Infinitude (although I can't use the UI, as developer mode breaks other things).  In production mode, it appears that data is being picked up by infinitude, but nothing shows up in the UI.  The UI also throws some errors in the dev console, and trying to query data through the API simply returns a "success" response, with no data.  Am I missing something?

**Comment by cfilkins** [comment]
I found that Infinitude is ignoring all of the requests coming from the thermostat, because the URL it's calling out to is just www.ioncomfort.com, so I was able to tweak the code to accept the requests.  I'm still having some issues getting any config data from the API, though...it just returns blank.  Looking through the code, there's something missing with systems.xml not getting saved (or read) properly.

**Comment by blinkwise** [comment]
Were you able to get this working? I am running into the same issue and have an ion system as well.

**Comment by scyto** [comment]
just fyi 'Websocket opened, but no streaming source found' i think this is normal when you don't have serial configured (aka shouldn't affect normal usage)

**Comment by audreez** [comment]
did you ever figure it out? i have the ion system as well and i see data coming in but nothing is displayed, see pic

![image](https://user-images.githubusercontent.com/12138529/154513357-f53046aa-139e-4064-84d6-607db4488aa8.png)

**Comment by kdjordjev** [comment]
I am also having issues getting from Bryant system 
[https://github.com/nebulous/infinitude/issues/129]

Any help appreciated

**Comment by nebulous** [comment]
I'll add `ioncomfort.com` to the list of whitelisted domains if it's compatible.

**Comment by audreez** [comment]
u da man, now its getting some/most of the data (see pic)
problem is i cannot control it from the app anymore and im getting these in logs, assuming this disabled passthrough is the problem, how to enable it?

thanks! how do i buy u a beeR?

![image](https://user-images.githubusercontent.com/12138529/154723921-61978127-2c8c-459f-84d4-13bd8b45e84d.png)
![image](https://user-images.githubusercontent.com/12138529/154724161-a5d194fd-11e1-4b0a-8ec6-846a53ff0554.png)

**Comment by nebulous** [comment]
Check your `pass_reqs` setting in infinitude.json. Infinitude talks to the thermostat much more aggressively than the manufacturer's API. To be a good citizen, we only forward requests to the OEM webservice at a maximum rate of every `pass_reqs` seconds which by default is 1020, or 17 minutes. You may set that value lower to see more traffic going out to Carrier (or in your case Ioncomfort I guess), but I wouldn't go lower than maybe 300.
