### ISSUE TITLE
Set Notification Reminder

### ISSUE THREAD

**Issue by rcoletti116** [nebulous/infinitude#117]
I've been testing to see if there is a way to interact with the notification reminders in infinitude. 

With the API I can turn reminders on and off as follows: PUT /api/config?filtrrmd=on / off
This allows control of the reminder function itself, which is not my aim.

What I would like to do is to perform a reset of the reminder, i.e. reset reminder and set filtrlvl back to 0.

I found the notifications-reminder.xml, which looks like an example of what I would want to control. https://github.com/nebulous/infinitude/blob/master/defs/notification-reminder.xml. However, I can't find anything that seems to allow change or control of these reminders in config or systems.

/notifications loads it's respective xml, but /notifcation-reminder does not.

Does such a function exist?

**Comment by nebulous** [comment]
The filter usage data is in status rather than config. `GET /api/status/filtrlvl` which is presently(and perhaps limited to - will need to investigate this) a read-only structure generated by the thermostat.
