### ISSUE TITLE
Cannot access schedules through carrier application with infinitude active

### ISSUE THREAD

**Issue by yomotherboard** [nebulous/infinitude#118]
I cannot access schedules, vacation, and heat source on the carrier myinfinity application when using infinitude. I installed infinitude of raspberry pi os. I was wondering if this is a bug, something I have misconfigured, or if it has just not been implemented. Thank you @nebulous for providing this tool!

**Comment by macWD** [comment]
@yomotherboard I have the same issue. I think it's because my model of thermostat is one without scheduling built in.

**Comment by yomotherboard** [comment]
I was able to turn on the scheduling again by going into the configuration of the thermostat. I had to hold the service icon until it turned green and in there there is a setting to turn scheduling back on. 

After that I had an issue with constant notifications from carrier about override commands from the thermostat. I guess it was trying to use its internal scheduling and infinitude's scheduling and so it go conflicting messages every time infinitude pushed a command. I think you have to set up schedules with infinitude if you enable the proxy server, or disable schedules with infinitude and manage them with the carrier app / thermostat.
