### ISSUE TITLE
multiple bryant controllers map to same zone name

### ISSUE THREAD

**Issue by ezavesky** [nebulous/infinitude#120]
Hello, I just got an infinitude proxy set up and am using the homeassistant integration for two Bryan Evolution Connex systems --- this was a weekend project done in less than an hour, so awesome work getting  us there!  

Unfortunately, it seems that the units both record status updates in infinitude with the same default name "ZONE 1".  So as expected there are race conditions in receiving updates in infinitude (e.g. set 'hold' on one unit and it will show that way until the next update) and sending updates from infinitude/homeassistant (e.g. setting a hold  will send a command  to one of the units but then the status gets confused again).

I know a few dev languages but am quite rusty with perl, so if there are some suggestions for where to look that would decorate or deference by an IP  (or serial?) in addition to a zone, I'd  enjoy hopping in  to see if I can't help.

Thanks  again for the tremendous work so far!

**Comment by nebulous** [comment]
Hi @ezavesky, I'm glad Infinitude seems to be working for you at least in part. Infinitude supports a single thermostat (multiple zones are fine) per instance. So if you have two separate systems that you'd like to control, the simplest solution is to run two instances of infinitude on different ports with different state folders. It may be possible to rename zones in one thermostat such that they don't conflict, but as I only have a single thermostat single zone system I'm unable to test such things.

**Comment by ezavesky** [comment]
Thanks this is great! I just spun up a second instance and all of the integrations work well.  Given how cheap the server is to run, I don't think there's any need to consolidate the devices, so I'll close this issue.  Thanks for the fast reply and again for the great work for this software-trapped device!
