### ISSUE TITLE
Question on Fan Mode Auto v. Always On

### ISSUE THREAD

**Issue by rcoletti116** [nebulous/infinitude#124]
Is there anywhere in Infinitude that supports reading if the Fan is in Auto or Always On Mode? I've looked through the APIs/data that I can find and don't see anything, but it's possible I've missed it or the field is not as obvious.

**Comment by dulitz** [comment]
Can't speak for infinitude, but as far as the bus is concerned, https://github.com/dulitz/finitude/blob/master/finitude/registers.py (my code) has a FanMode enum. The fan mode for zone 1 is in register 3b03 at offset 3 into the register data (offset 6 into the payload portion of the frame).

I would imagine that it's also in the data that infinitude proxies...

**Comment by rcoletti116** [comment]
Thanks for your insight @dulitz! I'd love to find a way that doesn't require serial connection.

**Comment by nebulous** [comment]
The only places it could ultimately be is in `systems.(xml|json)` or `status.(xml|json)`
I'll twiddle mine and see if I can find an obvious difference.

**Comment by nebulous** [comment]
Looks like you can tell the state of the fan, high/med/low/off, but not the setting which drives it. There's no obvious way that I see in the data to determine if the fan is currently high because it's set to stay on high vs high because auto commanded it.

**Comment by rcoletti116** [comment]
Thanks for checking. It's interesting that the function is not even in Carrier's own API documentation.

**Comment by GitHubGoody** [comment]
I just came across this situation in trying to write a custom status line using a Mushroom Template Chip.
![image](https://github.com/nebulous/infinitude/assets/46235745/f1819b2c-8f69-4b19-a2f2-f12c08c72925)

My workaround is that I assume if the fan is not in Auto that it must be set to Fan Only

Here are the relevant lines from the template:
```
{%- set fan_mode = state_attr(thermostat,'fan_mode')|capitalize %}
{%- set status_fan_only = 'Fan Only @ '+fan_mode %}
  {%- if fan_mode != 'Auto' %} {{ status_fan_only }}
```
