### ISSUE TITLE
Home Assistant "Unsupported Installation" found

### ISSUE THREAD

**Issue by Jaeger1985a** [nebulous/infinitude#125]
This was working great, until this morning when I get:

21-10-28 08:07:11 WARNING (MainThread) [supervisor.resolution.evaluations.base] Found images: {'nebulous/infinitude'} which are not supported, remove these from the host! (more-info: https://www.home-assistant.io/more-info/unsupported/software)

I have this running in Portainer, core-2021.10.6, supervisor-2021.10.6, Home Assistant OS 6.5.

**Comment by nebulous** [comment]
Hi @Jaeger1985a. This looks like more of a [Portainer](https://github.com/hassio-addons/addon-portainer#discontinued) integration issue. It appears Portainer is no longer maintained/unsupported. I can say however that I run multiple containers alongside Home Assistant using docker manually and HA doesn't notice or care.
