### ISSUE TITLE
Make sure thermostat is updated

### ISSUE THREAD

**Issue by binarypickle** [nebulous/infinitude#126]
Not an issue, so much as a PSA/FYI in case it is helpful to anyone else. I was running into an issue where my thermostat wouldn't send any data to the proxy server no matter what I did (and I tried a lot of things). It also wasn't connecting to the infinity api. After smashing my head against the wall, I realized that I hadn't checked the software version of the thermostat, and yep, it was several versions old. Used the SD card method to update and bam, it all works. So, make sure to try that if you're facing weird connectivity issues.

**Comment by binarypickle** [comment]
Firmware updates available at: https://legacy.myinfinitytouch.carrier.com/Infinity/Downloads

**Comment by nebulous** [comment]
Thanks, @binarypickle. You're correct that Infinitude doesn't go to much effort to support every version of the thermostat firmware - trading simplicity for convenience. But it's always most likely to work with my installed firmware version which if it helps at the moment is 14.02
