### ISSUE TITLE
Weird behavior if I turn off all schedules

### ISSUE THREAD

**Issue by brettonw** [nebulous/infinitude#128]
I have a weirdness - Using the [Home Assistant Integration](https://github.com/MizterB/homeassistant-infinitude), if I disable schedules entirely on infinitude, the integration will no longer connect. It might be an issue with the integration, but is there a reason this might not work as expected? I have to leave at least one scheduled transition to the Home comfort profile enabled in the list.

**Comment by nebulous** [comment]
I'm guessing this is an edge with the interaction between the HA Integration and Infinitude having to do with missing keys which are assumed to exist in the thermostat state store. You've already identified a workaround - have some transition, however meaningless - but if you want to pass along your systems.json file in the working and broken states, we should be able to spot the difference and fix it in Infinitude, or @MizterB might fix it in the integration, or both. Thanks for the report.

**Comment by brettonw** [comment]
Where do I find a systems.json file (not in the infinitude configuration directory, but there is systems+2ejson.dat). FWIW, I have two infinitude systems and both exhibit this behavior, so I suspect it's readily reproducible.

**Comment by nebulous** [comment]
http://yourInfinitudeIP:3000/systems.json should do it.

**Comment by brettonw** [comment]
[systems.json.zip](https://github.com/nebulous/infinitude/files/8100552/systems.json.zip)
both files zipped together.

**Comment by nebulous** [comment]
wow, ok. The _only_ difference between those two files is the single `enabled` key at
```json
["system",0,"config",0,"zones",0,"zone",0,"program",0,"day",0,"period",0,"enabled",0]
``` 

I think the HA integration may make an assumption that the zone is disabled if it doesn't have any enabled schedules.
Taking a quick look at its code, looks like the issue _might_ be around line 358 here:
https://github.com/MizterB/homeassistant-infinitude/blob/master/custom_components/infinitude/climate.py#L358

@MizterB can correct my assumptions though. Probably it would make sense to file an Issue with him mentioning what happens vs what you would expect to happen when a zone has no enabled schedules. (or workaround by leaving a single schedule enabled to Home 😉 )
