### ISSUE TITLE
I have lots of error-xxxxxxxxxx.xxxx files in the state dir - is this normal?

### ISSUE THREAD

**Issue by scyto** [nebulous/infinitude#13]
I have around 420 of these dating back to June 2015.  Let me know if they are needed else i can delete them!

**Comment by nebulous** [comment]
Feel free to delete them. Infinitude is intentionally a bit log-happy for debugging purposes.

**Comment by nebulous** [comment]
Looks like I have a few of those errors (6 over the last few months) - they look to be invalid/truncated xml files. possibly from broken connections to the Carrier servers, but that would be pretty frequent... 🤔 

as for SD card writes - yep I understand the worry, but it can be largely mitigated by using f2fs on your sd card. If you're really concerned about writes you can also mount your `state` folder as an in-memory filesystem, see `tmpfs` but that would be lost every reboot without some kind of periodic copying.

**Comment by Darkknight33** [comment]
Are there any downsides to the state folder getting periodically completely wiped (from using tmpfs)? Looks like there are more than just error files in there. Alternatively, if you can point me to a line I can comment out to prevent it from creating the error files, I’m happy go into the container and make that change for just in my setup, with the understanding that it wouldn’t survive container updates, etc. 

The writes from infinitude are not on their own a real concern, but in combination with all the other HA bits and pieces running on the same system, each writing data into to their own logs that, honestly, nobody will ever see, I do have some concern about the life of the card.
