### ISSUE TITLE
POST endpoint for the thermostat mode?

### ISSUE THREAD

**Issue by jftaylorMn** [nebulous/infinitude#134]
We have a (mostly) unoccupied place off the 'net that I would like to control at something lower than the lowest 50 degree setpoint for heat - save some energy while still keeping pipes from freezing.  One way to accomplish that might be to switch modes between "heat" and "off", monitoring the temp coming back from the thermostat.  I know from painful experience that the thermostat will display sub-freezing indoor temps while it is in heat mode (exhaust vent was complete iced over).   

It seems like that should be possible with a RPi and this code, but I am not familiar with the language and tools you are using, so don't feel comfortable contributing a PR.  I recall reading how setting values with infinitude has been flakey.  Maybe that's old info?  Point being, I would want to be confident that resetting to "heat" will happen when needed.

Thoughts?

**Comment by nebulous** [comment]
Technically yes, what you suggest is doable via Infinitude, but for something critical like that(especially where you can't monitor for problems and correct them remotely) I'd probably use a simpler solution like changing the thermostat's temperature sensor offset up to its maximum which would make what registers as 50 degrees be an actual temp of 50-offset.

**Comment by jftaylorMn** [comment]
Your point about failing safe is well taken.  I will not do this unless I am reliably logging to some time series database via IoT/cellular connection (another project).   With weak cellular there, even that's not certain.  

So, I would definitely prefer to use an offset as you propose.  With the thermostat a hundred miles away, sniffing for web traffic is not possible.   I'm stuck reading the thermostat manual online/searching for details on the web.  I don't see any references to offset in this Github repository. The only reference in the manual is with regard to a utility event response.  The docs don't say how low that event temperature can be.  The screen shot shows 51F.   To use that feature, I would need to know how to simulate a "local" utility event.  

It seems like the thermostat is the right place to adjust an offset (as opposed to the circuit board in the furnace).     Is this adhustment on some sort of "maintnenance" screen?

**Comment by nebulous** [comment]
If you hold the service icon for ten seconds, a service menu will appear with more options. One of which is offsets for temperature and humidity. I think you can set an offer of up to 5 degrees

**Comment by jftaylorMn** [comment]
A 5 degree shift should save at least a little propane (and help the planet in a very small way).  

I will be trying infinitude running with docker on a RPi 3 the next time we go there.  Everything is installed and seems to be running.  It would be even better if I can successfully send thermostat/system info via MQTT over a cell modem.  

Thanks for your effort to do what Carrier should have done from the start.   Between the wiki and GitHub, there is a wealth of detail.

I'll close this thread.

**Comment by nebulous** [comment]
You can definitely control infinitude via mqtt, the easiest way would be with Home Assistant and its infinitude integration. I run HA in a docker container and have been happy to have it set my thermostat to away when nobody is home etc.
