### ISSUE TITLE
I often have to kick start the serial stream by manually running readraw.py from brybus?

### ISSUE THREAD

**Issue by scyto** [nebulous/infinitude#14]
I noticed my state was 8mo old.

My Pi has been rebooted maybe a hundred times in that time.  The stream would not flow in the web page.  today i pulled the USB multiple times - no help.  I pulled the USB and pulled the power from the pi.  No help.

However once i ran readraw.py and saw it was scanning the bus I went back into the infinitude serial webpage and hit refresh - bang it was working.

I recall seeing this when i first setup infinitude too.  Any ideas?  One of those things?  Was it the hard reboot that might have been the trick?  something else?

**Comment by scyto** [comment]
hmm i just updated all files to latest infinitude and can't get the serial to work even after successfully running readraw.py - any ideas?
 
The default of '/dev/ttyUSB0' seems ok.

**Comment by treaves** [comment]
What is readraw.py?  It's not part of this app.

**Comment by nebulous** [comment]
I think @scyto was referring to a utility in https://github.com/3tones/brybus which is a python implementation of the Carrier/Bryant serial protocol. The issue unfortunately is transient so hard to debug. Anything which resets the serial tty will do, be that `readraw.py`, `cardump`, or any number of other serial tools like `setserial`. I'm leaving this issue open until I have the time and tuits to refactor Infinitude's serial code.

**Comment by kskenyon** [comment]
With my RS485 adapter I added:

stty -F /dev/ttyUSB0 0:4:cbf:0:3:1c:7f:15:4:0:0:0:11:13:1a:0:12:f:17:16:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0 &

to my /etc/rc.local and that seems to work.  Use stty to generate the proper command for your stubborn device.  Mine is CH340 based.

**Comment by nebulous** [comment]
https://github.com/nebulous/infinitude/wiki/Installing-Infinitude-on-Raspberry-PI-(Raspbian)#set-the-tty-baud-rate-for-the-carrier-38400-hvac-system-and-other-options
