### ISSUE TITLE
Can't change the current activity via the Comfort Profiles page when holding

### ISSUE THREAD

**Issue by butterkitty** [nebulous/infinitude#141]
Changing the current activity when holding via the "whole house" or by Zone doesn't work. No matter what is chosen, it will change to Home.

1. Navigate to Comfort Profiles page
2. Under "whole house" click the checkbox for hold and then use the dropdown menu to choose `away`
![image](https://user-images.githubusercontent.com/481603/158927618-3ae52ee3-798f-4f16-a9eb-336a9225974f.png)
3. Click Save.
4. Navigate to Status and then back again. It will have changed back to `Home`

Running latest docker image from dockerhub, updated today

**Comment by mamarley** [comment]
I thought I had fixed that in https://github.com/nebulous/infinitude/commit/7c5607b310d8c4a2fb76f1d788f602275cdec279, but I may have mismerged https://github.com/nebulous/infinitude/commit/226bf91590784e9fa3550137029fa0b94a66f203 and brought it back.  I will look in to it.
