### ISSUE TITLE
Infinitude only sees one thermostat

### ISSUE THREAD

**Issue by dustins1983** [nebulous/infinitude#146]
I got my infinitude portainer setup and working on a raspberry pi 2. I am able to see my 2 thermostats in the bryant app (which i couldnt do when I had it setup with a rpi1). I still however can only see one thermostat in infinitude.

When i go to localhost:3000 i see "zone 1" and thats it. Its my understanding I should see both of my thermostats in infinitude. Both of my thermostats have the proxy set up to go to infinitude, and they are both connected to the internet.

In the bryant app they were both named "Zone 1", which I changed to upstairs and downstairs. No change. Reboot, no change. This is on a complete fresh install of raspberry pi os, which i have run apt get update and upgrade. The pi is not used for anything else. I also tried to set up a windows docker and portainer, but I could never access infinitude, even though i can access portainer.

What am I missing?

**Comment by mamarley** [comment]
Each instance of Infinitude can only handle 1 HVAC system at a time, so if you have multiple systems, you need multiple Infinitude instances.

**Comment by nebulous** [comment]
mamarley is correct - Infinitude can handle multiple zones but not multiple thermostats. This is a limitation that stems primarily from the way the touch thermostats handle their update cycle. Adding support for multiple thermostats would add a level of complexity (and thus bugs) to Infinitude which isn't justified for the relatively small number of people who would like the feature. A single raspberry pi can run many instances of Infinitude, however. Many people choose to use the Home Assistant integration as well which is a fairly elegant way to integrate multiple stats/instances of Infinitude.

**Comment by GitHubGoody** [comment]
@nebulous I'm currently successfully running a single thermostat on Infinitude as an HA Portainer add-on container and using the Infinitude Integration to pull it into HA. I'd like to add a second and third thermostat to this setup. Your last two sentences above left me a little confused (...however...), so I just want to clarify the steps as I understand them before moving forward:

- Duplicate working Infinitude container to create instance #2
- Change port to 3001 on the copied container
- Change port to 3001 on the second thermostat
- Test Infinitude
- Explore solutions to bring in thermostat #2 and #3 into HA (https://github.com/MizterB/homeassistant-infinitude/issues/34) although I wonder if just changing the port to 3001 would also work there too.

Does that look right?

**Comment by nebulous** [comment]
That looks exactly right to me. I only have one thermostat and one zone, so haven’t tested this situation. Here’s my home assistant infinitude yaml:climate:  - platform: infinitude    host: 192.168.1.4    port: 3000    scan_interval: 300I’d think one could just add as many of those blocks as they had infinitude serversOn Jan 15, 2023, at 7:08 AM, GitHubGoody ***@***.***> wrote:﻿
@nebulous I'm currently successfully running a single thermostat on Infinitude as an HA Portainer add-on container and using the Infinitude Integration to pull it into HA. I'd like to add a second and third thermostat to this setup. Your last two sentences above left me a little confused (...however...), so I just want to clarify the steps as I understand them before moving forward:

Duplicate working Infinitude container to create instance #2
Change port to 3001 on the copied container
Change port to 3001 on the second thermostat
Test Infinitude
Explore solutions to bring in thermostat #2 and #3 into HA (MizterB/homeassistant-infinitude#34) although I wonder if just changing the port to 3001 would also work there too.

Does that look right?

**Comment by GitHubGoody** [comment]
OK, thanks. I'll give it a try this morning. How does the copied instance know to handle port 3001 traffic?

**Comment by GitHubGoody** [comment]
For those stumbling across this post, I’ve updated the Wiki with the steps that worked for me after reading through the Home Assistant Community post.

You can find it here:

https://github.com/nebulous/infinitude/wiki/Installing-on-Home-Assistant
