### ISSUE TITLE
energy.json - updated before midnight

### ISSUE THREAD

**Issue by home409ca** [nebulous/infinitude#157]
I have an unusual problem - question.
I have a thermostat in Home Assisstant - using the proxy inifninitude.

Is it possible for the proxy to update the energy.json file, for example, 10 minutes before midnight, rather than a few minutes after?

In HA, the energy consumption is attributed to me with the date "today" and not "yesterday", because the message received a few minutes after midnight, which is "today".

**Comment by nebulous** [comment]
energy.xml/json is posted to Infinitude from the thermostat - Infinitude can't request it from the thermostat, the timing of the values Infinitude has are completely dependent on when the stat posts them to the mothership - which does seem to be a bit after midnight.
