### ISSUE TITLE
Carrier Infinity Touch unable to reach www.api.ing.carrier.com when proxying through Infinitude

### ISSUE THREAD

**Issue by roseap42** [nebulous/infinitude#162]
This seems to have started on Jan 2, 2023. Had been working fine previously, but now unable to connect to the MyInfinity server at www.api.ing.carrier.com when proxying through my Infinitude instance. The docker server and the infinitude docker instance both can ping that server. When I disable the proxy on the thermostat, it connects right away. I'm still able to connect to the local Infinitude website and control the thermostat when it's connected to the proxy. I'm not sure whether something changed on my end, or with the carrier api endpoint, and I'm at a loss what to look for next. Any ideas to help me troubleshoot this?

**Comment by jftaylorMn** [comment]
Well,  something has changed, just need to figure out what...  I suspect that a lot of infinitude users don't use/care about the carrier server.  (I'm in that camp).  So... while unlikely, it's possible that an update to infinitude causing this could go undetected for a while.  

Here are some ideas to consider... Are you running the same infinitude code/release?  Could docker have pulled an update?  Did you upgrade the thermostat firmware (a known issue)?  If the infinitude web page is displaying current data, that's probably fine, but if the info is stale that might be a place to start.  Did you change your network security?  Are there any new/different messages in the log?  If not, then what remains is on the carrier side. 

The fact that the thermostat can communicate with the carrier endpoint when bypassing the proxy leads me to think that a new thermostat firmware update is a participant in this.  There is speculation that carrier has invoked some sort of encryption in the newer firmware. You can roll back to earlier releases by following the details in issue https://github.com/nebulous/infinitude/issues/159.  If that doesn't change the behavior,  it's simple enough to bring it to current.

**Comment by roseap42** [comment]
Thanks for the reply, and apologies for not getting back as quickly. Turns out, this morning I looked at the thermostat and it's once again connected to the carrier service. Probably something on the carrier api side that they broke, then fixed? I'm not going to over-think it. Cheers!

**Comment by adeelmysore** [comment]
I am having this issue on both of my thermostats. Anyone else?

**Comment by jftaylorMn** [comment]
The best way to isolate the root cause of this would be to temporarily change your thermostat settings to NOT use the proxy, then look for changes on the carrier site.  Assuming that your setup worked fine at some point and you have not updated the thermostat firmwaare, the Infinitude code may be to blame..  Since you have two thermostats, you could change only one for a direct side by side comparison.

If the problem can be isolated to Infinitude, I suggest opening a new issue instead of commenting on one that has been closed for quite a while.  The more detail the better when creating the issue.

Hope this helps.
