### ISSUE TITLE
Bryant Thermostat won't talk to Infinitude

### ISSUE THREAD

**Issue by TimothyJCowen** [nebulous/infinitude#163]
I'm having essentially the same issue as described by #129, however the solution from that issue does not apply to my situation.

My Infinitude is running on a Raspberry Pi with a Raspbian install. I followed the instructions on the wiki page that is linked in the Infinitude readme to set it up.

I can access Infinitude from other computers on my LAN, however it does not appear that my thermostat is actually communicating with Infinitude at all. The page looks like this all the time:
![Screenshot](https://user-images.githubusercontent.com/32042011/213898024-df9aab68-a986-4277-935f-393f0f5ea663.jpg)

I've tried this on port 80 and on port 3000 (by omitting the `-l` argument entirely), neither works. I _have_ changed the proxy address and port accordingly on my thermostat.

I did have the Bryant Android app set up prior to attempting to set up Infinitude, and I'm wondering if that might be causing a problem somehow? In any case, I would appreciate any assistance that can be provided. My ultimate goal is to connect the thermostat with Home Assistant. Thank you in advance!

**Comment by Grauwulf75** [comment]
I am also in the same situation, although on an ubuntu/docker install. I've tried various ports and both host and bridge network configurations to no avail.

**Comment by jftaylorMn** [comment]
If you haven't already done so, You should look at the firmware version of the thermostat.  If you have the most recent release, that may be the root cause of your problem. See https://github.com/nebulous/infinitude/issues/159 for more info on how to revert to an earlier version.

**Comment by TimothyJCowen** [comment]
> If you haven't already done so, You should look at the firmware version of the thermostat.  If you have the most recent release, that may be the root cause of your problem. See https://github.com/nebulous/infinitude/issues/159 for more info on how to revert to an earlier version.

This worked, thank you so much.
I think I'm going to add a PR later which adds a "troubleshooting" section, so that questions like this which are asked frequently can be answered in the documentation.

**Comment by nebulous** [comment]
I've recently been overwhelmed by other events, but am happy to accept PRs against the README as well as edits to the wiki! Don't be shy!
