### ISSUE TITLE
Additional RS485 Decoding - Questions

### ISSUE THREAD

**Issue by DrDeke** [nebulous/infinitude#164]
Greetings,

I have been doing some further decoding of the RS485 protocol on my Bryant Evolution (equivalent to Carrier Infinity) system based on the very useful information I found in your project here. In addition to what you have already worked out, I have discovered the following values on my (987M) system: 

* uint8 gas_valve_onoff - a boolean value representing the true on/off status of the furnace's gas valve
* uint8 gas_valve_percent - an integer value representing the modulating gas valve's opening percentage. note: even when the valve is off, this value shows 40% not 0%, so you also need to look at gas_valve_onoff
* uint8 hum_status - a boolean value representing the on/off status of the humidifier operated by the furnace

Details on these can be found at: https://github.com/DrDeke/bryantevolution/wiki/Interpreting-RS485-messages

I am hesitant to just edit your project's wiki to add these, for the following reasons: 

* I could be incorrect about some of these values (although the likelihood of this will decrease as I continue to monitor them)
* I am assigning arbitrary (and possibly uninformed) names to the newly discovered registers for some of these values
* I am only testing on my system, which is comprised of a 987M furnace and (come cooling season) a 186CNV air conditioner. I do not have any idea how or whether any of these values show up on other systems. 

I intend to continue attempting to decode the RS485 messages I see on the system bus, especially once the cooling season starts here. If/when I decode more useful/interesting messages, would you like me to create additional issues like this one, or is there some other method of contributing them that you would prefer? 

Thanks again for all your very useful work on this project!

**Comment by nebulous** [comment]
No need to be shy about editing the wiki - that's what it's there for, edit away! If you turn out to be wrong, just edit again.

Here's some recent data from my Carrier IDU(58CVA110) table `03 06` for comparison. It's also 10 bytes long but seems to be slightly different - maybe the following will be meaningful to you. How did you go about determining the above? Did you watch the stream on the computer and the furnace in real life?

heating
![image](https://user-images.githubusercontent.com/177510/215924721-790746d9-71fb-4f37-8458-ff96d4253453.png)

heat cycle ending
![image](https://user-images.githubusercontent.com/177510/215925322-00760816-4885-4fb8-986d-c6bfeb5cc433.png)

byte 2-3 is blower rpm like yours, and the last byte `0x08` may be my humidifier status, especially if it's a bitflag on the top bit of the lower nibble: `00001000b`

**Comment by DrDeke** [comment]
Thanks for the response (and additional data)! I have added the three variables I discovered to your wiki and will continue to update it if/when I discover more.
