### ISSUE TITLE
Not working with ION Home Comfort 

### ISSUE THREAD

**Issue by blankmansb** [nebulous/infinitude#168]
I have set up the portainer Proxy and installed and configured the homeassistant/Infinitude integration but it isn't pulling information from the Thermostat.

The ION thermostat is confgured to point to the proxy server.

On the proxy server I  get this message:

[8] [info] Websocket opened, but no streaming source is available

On the Web browser I get this

 
![Infinitude](https://user-images.githubusercontent.com/44474763/225110821-97f89f6f-fc63-42e4-8603-b9244f95a417.jpg)

My configuration in homeassistant is

climate:
  - platform: infinitude
    host: 192.168.0.xx
    port: 3000
    zone_names:

Any help would be appreciated

**Comment by nebulous** [comment]
> [8] [info] Websocket opened, but no streaming source is available

this is purely informational - related to an optional serial feature.

what does `/api/state_keys` return? The above screenshot looks like the thermostat hasn't phoned home via Infinitude yet. Which could be a configuration issue, a version issue, a network permissions issue, any number of things.
