### ISSUE TITLE
Novice trying to get off the ground...

### ISSUE THREAD

**Issue by dookie-x** [nebulous/infinitude#169]
Apologies up front for the likely numbskull issue here, I'm a network guy but new to Synology/Docker/HA. Thus far, I have managed to get both HA and Infinitude running in Docker containers on a Synology NAS. Sort of...

Possibly complicating things: my thermostat is on an IoT VLAN, which can respond to but not initiate conversations with the primary VLAN where the NAS resides (both have free access to the internet). Thermostat is communicating w/Carrier properly (their app still works as expected).

My thermostat is configured with a proxy at NAS:3000. Both the HA and the Infinitude containers are using the Docker host network (ie: not a bridge) on their native ports (8123 / 3000). If I point a browser there, I see a blank Infinitude UI...no data, but I do get the UI. HA starts and runs as expected, save Infinitude. I've edited my configuration.yaml (I think) appropriately, and when HA starts it calls out the custom integration, but no further complaints. Relevant section of the config file:

"# Infinitude add-in
climate:
  - platform: infinitude
    host: NAS
    port: 3000
    zone_names:
        - Main"

Then when HA starts, first it calls out the custom integration as expected, but then it fails as follows:

"Error while setting up infinitude platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/infinitude/climate.py", line 111, in setup_platform
    zones = status["zones"][0]["zone"]
TypeError: 'NoneType' object is not subscriptable"

I guess my question is why isn't Infinitude able to retrieve data from Carrier, thus showing the blank UI? It does show the globe in blue. I'm assuming that once there is data available, HA should be ok...

**Comment by nebulous** [comment]
> Possibly complicating things: my thermostat is on an IoT VLAN, which can respond to but not initiate conversations with the primary VLAN where the NAS resides (both have free access to the internet). Thermostat is communicating w/Carrier properly (their app still works as expected).

I would guess that's at least _one_ problem. A tcp connection will need to be established originating from the stat to Infinitude for the proxy connection.

**Comment by Elder-HVAC-Man** [comment]
Did you come up with a solution to this?  Having the same problem, but on the same network.
