### ISSUE TITLE
Request to have Rest Calls for Mode (heat/cool/fan only/off)

### ISSUE THREAD

**Issue by waynehead99** [nebulous/infinitude#17]
Would like to see if you can add this into the rest API?

Thanks

**Comment by nebulous** [comment]
Wrote this on my lunch break, so haven't had a lot of time to test. Reopen this issue as needed.

Added an endpoint to get/set any **single valued** system variable by path. This is for basic settings. Not trying to reinvent XPath here. This is quite flexible, but as such it does zero validation. Meaning it will set your mode to heat, cool, or banana if you ask it to. 


Mode example:
examine single variable `/api/config/mode`
examine entire config structure `/api/config`

set mode `/api/config?mode=heat`
set mode and backlight at once `/api/config?mode=cool&blight=70`
