### ISSUE TITLE
Repeated messages in Syslog - Question

### ISSUE THREAD

**Issue by greggitter** [nebulous/infinitude#175]
Infinitude has been working well, integrated with HA and today I happened to check the syslog and noticed these messages repeating every 1 minute.

```
Jun 26 15:19:49 ct-Other infinitude[157]: [2023-06-26 15:19:49.47739] [157] [info] systems-1721W00xxxx-status cached or passthru disabled
Jun 26 15:19:49 ct-Other infinitude[157]: [2023-06-26 15:19:49.47780] [157] [info] /systems/1721W00xxxx/status
Jun 26 15:19:49 ct-Other infinitude[157]: [2023-06-26 15:19:49.48230] [157] [info] Saving status
```

What are these messages and can it be fixed to resolve the messages or suppressed?  How?  Much appreciated!

Thanks!

**Comment by nebulous** [comment]
sure. those messages are at debug level `[info]` so there's nothing really broken that needs to be "fixed" but you can adjust your logging settings to a different level with environment variable `LOGLEVEL`. The available levels are from most-to-least verbose: trace, debug, info, warn, error and fatal

**Comment by greggitter** [comment]
Ah...OK makes sense. I tried adding the environment variable to the service line in the systemd config but it errors out (I'm using native, not docker).  Tried these and none work...fails to start.

ExecStart=/opt/infinitude/infinitude daemon -m production -e LOGLEVEL error -l "http://:3000" &>/dev/null &

and....

ExecStart=/opt/infinitude/infinitude daemon -m production -e LOGLEVEL=error -l "http://:3000" &>/dev/null &

and....

ExecStart=/opt/infinitude/infinitude daemon -m production -l "http://:3000" &>/dev/null & -e LOGLEVEL error

In the meantime I commented out all the log lines in the source...which works fine.  :)  Thanks!

**Comment by nebulous** [comment]
- commenting out the log lines is guaranteed to work! :)

- if you're already going to the effort of modifying source, it would be easier to change [the loglevel here](https://github.com/nebulous/infinitude/blob/master/infinitude#L515) to `'error'` 

- As far as I know Mojolicious doesn't support the concept of setting env vars with `-e`, but if this is a systemd service file I think you may be able to just set the env in the exec line like so...
`ExecStart=LOGLEVEL=error /opt/infinitude/infinitude daemon -m production -l "http://:3000"`
or worst case, make a bash wrapper script to do the same.

**Comment by greggitter** [comment]
Thanks.  Just went and tried that per above, but unfortunately doesn't work...fails to start.  No worries....I'll tweak it in the source.

Cheers!  :)
