### ISSUE TITLE
How do i figure out which stage the A/C is running at via the API?

### ISSUE THREAD

**Issue by nitrogen76** [nebulous/infinitude#176]
Hopefully a dumb question.  How do I figure out which stage the AC is running at (e.g. stage 3) via the API?

I can't find an obvious JSON data object that has that information under /api/status, but I do see it in the infinitude data on the webpage, so i am assuming it's available in the api somewhere, somehow.

**Comment by nebulous** [comment]
that will be different depending on your components so I can't answer directly without a bit more info, but can say if it shows up on the infinitude webpage you're right that it should be accessible. The two primary sources for all data from the stat are `systems` and `status`, accessible as /systems.json /status.json (or .xml if you're masochistic) 

if you can't find it in one of those, send a screenshot of where you see the value and I'll try to help drill down.

**Comment by nitrogen76** [comment]
ok, /systems.json is what I needed.

Thank you so much for your quick help?  Was that in the documentation?  I didn't see it in the wiki.  If it's there, where should I have looked?  If it's not i think it'd be a good addition to the wiki at least

**Comment by nebulous** [comment]
Likely that's not in the wiki since ~I'm lazy and documentation is hard~ api calls assume a higher level of understanding of the mechanisms in Infinitude, but you can definitely feel free to edit the wiki that's what it's there for!

**Comment by nebulous** [comment]
for more context, `/api/config` wraps around the config key within the raw systems.json so if you found it in systems.json it should also be available at /api/config, and you can get the value directly at /api/config/whatever/path/to/the/value
