### ISSUE TITLE
Wiring into the control box?

### ISSUE THREAD

**Issue by treaves** [nebulous/infinitude#18]
I see nothing on how to wire the three terminals into the Carrie control module.  Have I just missed it?

**Comment by nebulous** [comment]
This might be what you're looking for:
https://github.com/nebulous/infinitude/wiki/Infinity-Protocol-Hardware

Though I would caution against using Infinitude if you have trouble with this type of thing unassisted.

**Comment by treaves** [comment]
Thanks.

Yes, I had seen that.  And I'd like to make sure all of the equipment I have is documented on the  hardware page; I have a new, high-end system with I think every option you can get.

I was meaning if there were a particular place that was better/worse to actually put the wire from the interface module into the control unit.  My control unit -I have a four zone system - has many blocks I can jump to, and I just wondered if one would be better than the other.

**Comment by nebulous** [comment]
The data rate is slow enough that it can tolerate a bit of reflection/impedance mismatch. If you use _short_ lengths of similar gauge thermostat wire then probably any point along the bus will work out just fine to get clean serial data.

**Comment by treaves** [comment]
All four of my thermostats (The Infinity Touch in zone one, and the other three zone's thermostats) all go into the Zone Control Box with four wires each, ganged into the two on-board ABCD blocks.  This would seem the logical place to wire into it.  And as they are all in parallel, I should be able to use (proper) wire of just about any length.  In my case, about 15' gets me to my network box, with my 48 ports of Cat 6e patch panels & switches.  I can place the Pi there with the serial/usb adapter.
