### ISSUE TITLE
Home Assistant Addon

### ISSUE THREAD

**Issue by sosheskaz** [nebulous/infinitude#181]
Hello, I have created a home assistant addon for infinitude at https://github.com/sosheskaz/infinitude-ha-addon.

Is there any interest in integrating it into this project, or adding it to the README at the end? Also would not mind code review of my implementation, especially the config injection strategy.

I'd be happy to maintain it, although my release cycle is still immature and I may make significant changes in future, i.e. immutable versioning and more complete docs.

**Comment by nebulous** [comment]
I'm open to integrating, setting up a submodule, pointing in documentation, or whatever makes sense. Can you provide some details as to how you might want it to work?
