### ISSUE TITLE
Quick question: "mode" is it controllable?

### ISSUE THREAD

**Issue by electricessence** [nebulous/infinitude#182]
I have a hybrid system where it lets me change from heat-pump to gas heat.
Can I control this through the API?

**Comment by dragonflight** [comment]
see issues #88, #166 (long reads for info only) and the wiki for making
changes to attributes
The attribute you want is *heatsource* and the values are {"*system*"
(system control) | "*odu only*" (heat pump) | "*idu only*" (gas or electric
strip heating)}

**Comment by electricessence** [comment]
Ok great!  Now at least I know it's possible.
I'm seeing "gasonly" "hponly" and "off" as the values it reports.

**Comment by electricessence** [comment]
Follow up:
This worked for me!  Thank you!!!

**Comment by dragonflight** [comment]
I'm a bit surprised that those are the only values. I would expect there to
be a value for system or auto.
I have a heat pump/strip(electric)heat so I can't really help you, but
others have reported a value of 'idu only' for gas.
You can change the source in the thermostat and one of the choices is
"system controlled" (at least on mine). You might want to see what it then
reports in 'heatsource'

**Comment by electricessence** [comment]
I take it all back.  this is what I have:
"heatsource" is exactly as you said.
But "mode" which comes back from the status has various values like "hpheat" etc.

**Comment by dragonflight** [comment]
And now I see the confusion (I think).

There are several "mode"s
The one returned in STATUS is what is currently happening. On mine I see
hpheat, hpelectheat, hpcool. I don't know if there are others if the system
has a humidifier, air exchanger or what have you.
It is the current status and as such is read only.
There is a "mode" in CONFIG that sets heat, cool, auto, fan only, off.
In systems with multiple heat sources there is "heatsource" in CONFIG that
allows you to force the system to use a particular heat source or allow the
system to choose depending on various parameters in the system setup

Hope this helps

**Comment by electricessence** [comment]
Yep.  Got it.  Working great. Thank you.
