### ISSUE TITLE
POST to set hold is returning XML instead of JSON

### ISSUE THREAD

**Issue by MizterB** [nebulous/infinitude#185]
There seem to be differing behaviors from Infinitude when POSTing a hold command...

On my system, a POST to `http://host:3000/api/1/hold` with `{'hold': 'on', 'activity': 'manual', 'until': '06:30'}` is returning a JSON response of `{"activity":"manual","hold":"on","until":"06:30"}`.

On the system referred to below, the exact same call appears to be returning the system config XML.
Please see https://github.com/MizterB/homeassistant-infinitude-beyond/issues/2

**Comment by ac-haynes** [comment]
I don't have a root cause, but I deleted the container volume, and redeployed latest and it started returning JSON responses. I had been using the same persistent docker volume for ~2 years.
We can close this out unless you want to troubleshoot it

**Comment by MizterB** [comment]
If that's the case, I don't think we need anyone spending time troubleshooting old code.  Thank you for the update.

**Comment by nebulous** [comment]
yep - this was a bug previously fixed. The latest container should return json by default.
