### ISSUE TITLE
API Endpoint for Checking Infinitude Version

### ISSUE THREAD

**Issue by MizterB** [nebulous/infinitude#189]
Some users of Home Assistant's Infinitude Beyond integration are getting errors due to running an older version of Infinitude.  An example is here: https://github.com/nebulous/infinitude/issues/185

Is it possible to query Infinitude for version information so this can be handled gracefully?

**Comment by nebulous** [comment]
Not really 🫤 - I could add such a thing, either returning some monotonic integer or perhaps the git hash or a build date, but it would only be useful in newer builds. Happy to do so if that will be useful.

In this case however, I think the ugly format detection strategy is the best option - either by returned content type header or by first character.
