### ISSUE TITLE
Issue running the app

### ISSUE THREAD

**Issue by treaves** [nebulous/infinitude#19]
When I `./infinitude --help` or any other command line, it dies with the following error:
`Use of uninitialized value $ENV{"MOJO_MODE"} in string eq at ./infinitude line 49.`

I see this is just what it says; a default should be set however.

**Comment by treaves** [comment]
Once the app is running (as following the instructions on the main page), I can load the app in my browser.  However, this is a snippet of what I get:

**Comment by nebulous** [comment]
Could you provide the output of the Infinitude tests? `prove -v` from your Infinitude directory.

**Comment by nebulous** [comment]
I'm going to close this issue since I didn't get a reply. Likely the above is due to missing dependencies. If you're using a Raspberry Pi, perhaps this documentation link will help
 
https://github.com/nebulous/infinitude/wiki/Installing-Infinitude-on-Raspberry-PI-(raspbian)

Feel free to reopen if you have new information.

**Comment by 7ooL** [comment]
I get the same error
```
 ./infinitude test
Can't find serial device: /dev/ttyUSB0. Serial monitoring disabled.
Use of uninitialized value $ENV{"MOJO_MODE"} in string eq at ./infinitude line 49.
Running tests from "/home/host/infinitude-master/t".
/home/host/infinitude-master/t/00-depends.t ............ ok
/home/host/infinitude-master/t/01-xml-simple-minded.t .. ok
/home/host/infinitude-master/t/02-cache-filedump.t ..... ok
/home/host/infinitude-master/t/system-post.t ........... Can't find serial device: /dev/ttyUSB0. Serial monitoring disabled.
Use of uninitialized value $ENV{"MOJO_MODE"} in string eq at /home/host/infinitude-master/t/../infinitude line 49.
/home/host/infinitude-master/t/system-post.t ........... 1/9 Use of uninitialized value in concatenation (.) or string at /home/host/infinitude-master/t/../infinitude line 239.
/home/host/infinitude-master/t/system-post.t ........... ok
All tests successful.
Files=4, Tests=42,  6 wallclock secs ( 0.04 usr  0.01 sys +  1.67 cusr  0.12 csys =  1.84 CPU)
Result: PASS
```

i have also seen 
```
 Use of uninitialized value in join or string at ./infinitude line 385.
```
I take it it comes from not having the serial monitoring, is there a way to disable it permanently?
