### ISSUE TITLE
Carrier CRC2-NTC Thermostat

### ISSUE THREAD

**Issue by darioaxel** [nebulous/infinitude#190]
Hi,
 
I'd like to sustitute my old CRC2-NTC Thermostat that Carrier used to install in systems as 40DMC series in Europe with an ESP32 with touchpad. 
I'm trying to capture and decrypt the data the thermostat sends to the unit .. but I'm not getting anything valuable. 

Does anyone know how could this work? It says that the system uses CNN but.. the streams of bytes are really not consistent... every time i get a different dataset.

Thanks!

**Comment by nebulous** [comment]
Hey @darioaxel - you might have better luck with this request on forums such as cacoontech. I'm not familiar with the thermostat you mentioned, but looking at its installation manual online, it doesn't appear to be communicating in the same manner that Infinity systems are.
