### ISSUE TITLE
Rest calls to change mode?

### ISSUE THREAD

**Issue by mrzarquon** [nebulous/infinitude#2]
It looks like right now I can only change settings for predefined profiles and schedules, but if I wanted to have a remote system be able to trigger holding a different profile (ie, a vera or similar zwave controller has rest api abilities), would that be possible?

Being able to have that system toggle between home, away, sleep, wake would be before and allow for one to use the motion detection / sensors / scene capabilities of the vera to handle figuring out which is the right profile for the moment.

**Comment by nebulous** [comment]
That would be possible and is listed in the todo.txt. Since I haven't needed that personally, I haven't prioritized on the feature. If you would like to participate in testing that out, I'll be happy to write it.

**Comment by mrzarquon** [comment]
I'd definitely be up for testing, something as simple as hitting setprofile/away to switch to away would be sufficient for my needs (and getprofile/ returning the current active profile), the intelligence of when to do that I can handle on my end.

**Comment by nebulous** [comment]
The current status is already available at /status.xml or /status.json as well as the complete configuration at /systems.xml or /systems.json

As for setting status, I added a quick and dirty action to allow for setting a hold, which is what the stat does if you just walk up to it and change settings.

works for all http types right now for your testing simplicity, but I'd like to narrow that down to PUT/POST

/api/yourZoneIdMostLikely1/hold?activity=(home|away|sleep|wake|manual)&until=HH:MM&hold=(on|off)

**Comment by nebulous** [comment]
added additional endpoint to change heat/cool/fan settings for each activity

/api/yourZoneIdMostLikely1/activity/(home|away|sleep|wake|manual)?htsp=99&clsp=60&fan=high

**Comment by nebulous** [comment]
@mrzarquon tried them out and they work on my system. Let me know how it goes for you.

**Comment by nebulous** [comment]
@mrzarquon - have you been able to test this? Anything I can do to assist?

**Comment by mrzarquon** [comment]
This notification got buried in my work related ones. I'll have a chance to test this weekend, but this is looking promising!
