### ISSUE TITLE
missing templates

### ISSUE THREAD

**Issue by smartcanada** [nebulous/infinitude#20]
i followed the (new) instructions for install and still have the following errors executing infinitude:

[Wed Oct 26 14:16:45 2016] [debug] GET "/systems.json"
[Wed Oct 26 14:16:45 2016] [debug] Routing to a callback
[Wed Oct 26 14:16:45 2016] [debug] Template "key.json.ep" not found
[Wed Oct 26 14:16:45 2016] [debug] Template "not_found.development.json.ep" not found
[Wed Oct 26 14:16:45 2016] [debug] Template "not_found.json.ep" not found
[Wed Oct 26 14:16:45 2016] [debug] Template "not_found.development.html.ep" not found
[Wed Oct 26 14:16:45 2016] [debug] Rendering cached template "not_found.html.ep" from DATA section
[Wed Oct 26 14:16:45 2016] [debug] 404 Not Found (0.010761s, 92.928/s)

**Comment by nebulous** [comment]
I'm glad to hear things went more smoothly. The above aren't actually errors, but debug messages. They should not appear if you run infinitude in `production` rather than the default `development` mode. 

`./infinitude daemon -m production`
