### ISSUE TITLE
Couple questions about display, data and wunderground

### ISSUE THREAD

**Issue by 7ooL** [nebulous/infinitude#23]
Thanks for your work, i have it working completely almost....

I do not have the serial bus reading as im just using the wifi to connect. all the test passed. But i have some questions to help be better understand the whole thing, before i start adding in other smart objects to the gui. 

1) Where does the "Outside" "Blower" "Coil" and "Airflow" data come from in your screenshot, should those graphs be showing when connected by wifi only or are they only accessible off the serial bus?
![image](https://cloud.githubusercontent.com/assets/11856305/21206829/67b5e4ee-c232-11e6-938f-3755f1288b53.png)
2) I also have some display errors, with words overlapping, as you can see in the picture. This may be able to be adjusted in a css file. I have tried a giant 4k monitor and it still displays that way. 

3) lastly, i added my wunderground key to the config section in infinitude as well as in the infinitude.json file. How do i know if it's pulling data from there. Are there any maps on the front end or is it all backend data? Is wunderground data populating my actual weather information on the wall mounted infinity control unit?

**Comment by nebulous** [comment]
- 1 Those items are read from the serial bus, though outside air temp is also available via the http interface
- 2 What browser are you using? It's probably obvious that I'm not so great with UI :) but in my case (Chrome on Mac/Linux) a different, less bold, font appears to be selected.
- 3 presently Wunderground is used to replace Carrier's weather service. Infinitude is designed to be functional with or without a connection to Carrier's web service, so your wall-mounted unit would get weather from wunderground your key is set. To test a forecast hit the following url:
    http://yourInfinitudeIP/weather/zipCode/forecast
    for instance: http://10.0.0.4/weather/90210/forecast

**Comment by 7ooL** [comment]
1) i wonder why i'm not getting an outside temp then..? I went ahead and order the serial bus adaptor i like the extra information. 
2) chrome on windows, safari on iphone, MS Edge on windows all displayed the same, no big deal, i'll eventually start messing with the css file. 
3) great information. any thought to adding weather radar/forecast to the front end?

**Comment by 7ooL** [comment]
/infinitude/public/dist/index.html line 23 ```css  font-size: 1.2em``` fixes the text being too large.
![image](https://cloud.githubusercontent.com/assets/11856305/21251429/a04bde6e-c31b-11e6-8392-1c4a35f72c2e.png)
whats the differnence between `infinitude/public/dist/index.html` and `infinitude/public/app/index.html` modifiing /app/index.html did not make any differnce.

**Comment by nebulous** [comment]
Infinitude uses Grunt as an asset builder. `public/dist/*` is the output of the build process. If you modify `/app/*` then run Grunt, the dist files will be changed accordingly.

**Comment by 7ooL** [comment]
i can't seem to find where, current humidity (rh), temp (rt), and set points for hot and cold (htsp, and clsp) are, i'm not seeing it in the full config call or in the zone call. how do i query that information. If i don't have to pull the entire config that would be best. 

how do i api call current temperature and humidity status?

**Comment by nebulous** [comment]
There are two primary structures provided by the stat/Infinitude: `config` and `status`. Config is the larger of the two and contains the configuration of the device: profiles, temp settings, etc. Status contains a brief summary of the current state. As with all api call structures, Infinitude exposes them as both xml and json to suit your needs. (for instance http://yourInfinitudeIP/status.json) The table at the bottom of the main tab is a direct dump of the status structure, so anything you see there will be in status.json/status.xml

**Comment by 7ooL** [comment]
thank you, status.json has the information that i wanted. Your last comment contains valuable information that should be added to the api section. I'm basically using infinitude to open up and api to my hvac system so that i can integrate its information into other smart appliances/devices and begin to assemble a whole home solution.

**Comment by 7ooL** [comment]
I appreciate the help you have been providing, im making great strides using infinitude as a source for HVAC information. I'm not moving into making the comfort profiles more dynamic. 

I can easily set the the profile and hold using: http://myip:3000/api/1/hold?activity=sleep&until=18:45 command. Any thought of using the put commands for the api?

how would I configure vacation mode via the api? activity=vacation from=? until=?
i see a vacstart and vacend variable, not sure how it would like the date time passed into it. I also think that calling the "http://myip:3000/api/config" url clears out planned vacations set via the touch interface.

**Comment by 7ooL** [comment]
the size being to big doesnt not come from your CSS file but the vendor file. no big deal i just changed the file on my end to look better.
