### ISSUE TITLE
Humidity goes to NaN

### ISSUE THREAD

**Issue by 7ooL** [nebulous/infinitude#24]
if there interfaces remains open, eventually the humidity output goes to NaN.
![image](https://cloud.githubusercontent.com/assets/11856305/21290414/63034110-c487-11e6-870d-e429870094df.png)
rh in the table below remains an actual number
![image](https://cloud.githubusercontent.com/assets/11856305/21290416/7b67cf46-c487-11e6-984a-7aa5e54b9f45.png)

**Comment by nebulous** [comment]
Do you happen to know if it recovers after a few minutes, or after switching tabs back and forth, or does it require a refresh?

**Comment by actualJeremyBenscoter** [comment]
I also have this issue.

It does recover intermittently, I just had NaN and it came back a few minutes later. Changing tabs did not fix it. A refresh does fix it.

I do see some errors in the browser console:
![image](https://cloud.githubusercontent.com/assets/24662541/21651857/4d2cfa62-d278-11e6-9f13-fef74c867f33.png)

**Comment by xeroiv** [comment]
I am seeing the same error happen here in line 2 of vendor.js.  I am using Chrome 81 to view the infinitude server.  There are a few more errors in the log as well.

Would these errors also contribute to the fact that my OAT field is null?  I assumed that as long as I enabled the local weather forecast service on the thermostats that I could get this data, but it doesn't appear to work.

![image](https://user-images.githubusercontent.com/6626311/83054164-f69aec80-a01f-11ea-8e6b-4d81c8298d89.png)

**Comment by MallocArray** [comment]
I see the same thing if I leave the tab open in Chrome.  If I refresh the page, the the humidity meter and Outside temperature meter refreshes with correct data.

The meters for Zone 1 consistently stay working even with the tab being open.
