### ISSUE TITLE
Use of uninitialized value error when trying to set hold

### ISSUE THREAD

**Issue by actualJeremyBenscoter** [nebulous/infinitude#25]
I get two errors when I try to set the hold temperature of the thermostat. It also does not seem to set anything in the thermostat. I am using the Carrier Infinity model without a serial connection. 

I get two errors:
`'Use of uninitialized value in string eq at ./infinitude line 128.'`
`'Use of uninitialized value in lc at ./infinitude line 132.'`

The request I am making is (using postman):
POST http://*:80/api/1/hold

Sent as raw data in PostMan
activity=manual
htsp=73
until=14:00

**Comment by actualJeremyBenscoter** [comment]
Disregard this. Error shows up, but thermostat does get set. I just didn't realize they were query string instead of JSON.

Carry on and keep up the great work!

**Comment by nebulous** [comment]
Yep, the API takes form parameters rather than json as an input. It even violently breaks REST by allowing GETs to make changes because some home automation controllers can only send GETs.
