### ISSUE TITLE
More Device Tables

### ISSUE THREAD

**Issue by woody1961** [nebulous/infinitude#26]
This is for a SYSTXCCITC01-A thermostat on an Infinity Greenspeed System if you want to add it to the protocol breakout:

Device	Table		Name
20		0x01		DEVCONFG
20		0x02		SYSTIME
20		0x03		INGUI
20		0x04		SSBCAST
20		0x06		LINESET
20		0x3b		SAMINFO
20		0x40		SCHEDULE
20		0x41		TEMP
20		0x42		LASTTEN
20		0x46		MISC1
20		0x47		RESTMR
20		0x48		HEALTH
20		0x49		SYSCTRL
20		0x4a		MISC2
20		0x4c		SYSMETRC
20		0x4e		CHARGING

**Comment by ehwest** [comment]
The SAMINFO is the table of interest.
It seems the rows 3B02 and 3b03 are coughing up zeros for the newer "touch" models and most of the good data for the older models.
Can you expore the contents of other rows on this table?
Change your code to request rows  3b04, 3b05

**Comment by woody1961** [comment]
All the rows for SAMINFO were empty (zeros). I scanned (if I recall correctly) all the way up from 0x01 through 0xaf and did not find any additional tables.

**Comment by ehwest** [comment]
Ok, nice work.   Now we have a bigger mystery...in what table is the thermostat data located for "touch" thermostats....
I think we need to scan them all or find someone with a SYSTXCCRCT01 SAM set up where we can run wireshark or something.   

I noticed there are dealers selling SAM (RJ45)  version.  My dealer told me Carrier has discontinued the SAM and will be updating software for the touch thermostats to provide access in some way.

**Comment by ehwest** [comment]
I suppose its possible the Touch thermostat just doesn't cough up the needed data.
