### ISSUE TITLE
Rasperian Install Instructions not working

### ISSUE THREAD

**Issue by ehwest** [nebulous/infinitude#29]
Instructions on how to install the perl modules is missing.

**Comment by bvarner** [comment]
Are you talking about on raspian?

https://github.com/nebulous/infinitude/wiki/Installing-Infinitude-on-Raspberry-PI-(Raspbian)

**Comment by nebulous** [comment]
I think @bvarner's reference should cover it, but if not could you define which modules specifically you're having trouble with?

**Comment by bvarner** [comment]
Exactly why I was asking. :-)

**Comment by ehwest** [comment]
Yes, very sorry.  
There is a funny glitch after running sudo apt-get upgrade
where it is ambiguous as to whether its done or not.
You can close this.
