### ISSUE TITLE
ASCII Protocol Information

### ISSUE THREAD

**Issue by johnnyo21** [nebulous/infinitude#30]
Just wondering if anyone has seen this document. Might make uncovering the meanings of the ASCII commands and responses a little easier.

[](http://www.utcccs-cdn.com/hvac/docs/1009/Public/01/SAM01-02XA.pdf)

Let me know if this helps, I have access to more documentation if need be.

**Comment by johnnyo21** [comment]
The URL doesn't seem to have gone through.  Is there a way I can upload a PDF?

**Comment by nebulous** [comment]
Hi @johnnyo21, if this is the Carrier document specifying the ASCII protocol for the System Access Module (Carrier document ID SAM01-01XA) then I believe we have seen it, but thanks for pointing it out. Unfortunately that document defines how to communicate with an _absurdly_ priced intermediate box which translates simpler ASCII commands over RS232 into other commands on the RS485 ABCD bus. What all of us really need is someone with a SAM to record commands in and their resulting outputs. Particularly during the bootup/discovery sequence.

**Comment by johnnyo21** [comment]
Oh I see, I didn't realize the ABCD was RS485.  I am just getting started with setting up a home automation system and I came across this. I wish Carrier had a better solution for us. I might be able to borrow a SAM for a while and test.  Looks like I need to purchase some things and get going.  Thank you for your work on this by the way. I would like to help out if I can.
