### ISSUE TITLE
Question:  pulling currentActivity from status

### ISSUE THREAD

**Issue by sejgit** [nebulous/infinitude#31]
First thank you for answering & fixing my last question on the man-in-the-middle issue.
Sorry to ask what is likely a basic question.
I have been able to change activity, holds, & settings ; as well as get status on many things, but am frustrated in how you are getting the currentActivity from status.
I can get the complete status but it does not seem to hold the currentActivity yet you have it on your status page.
Spent a few hours in your code but am new to JSON & modilicious & cannot seem to figure the hierarchy.
Seems to me the get should be something like:
10.0.1.15/config/1/currentActivity   but not only does that not work but does not seem to be in the status definition like that.
would you mind taking a minute to answer ; sorry for the bother but am frustrated.
thanks so much.

**Comment by nebulous** [comment]
CurrentActivity is in status under each zone. You can access status at `/status.json` or `/status.xml` For example, in my single zone system, the current status is "away"

status->zones->zone id 1->currentActivity

how are you attempting to load status, and how would you like to load it?

**Comment by sejgit** [comment]
Appreciate the response...
I am trying to query from an ISY994i using REST requests.
Have mastered full config pulls,holds & switching activities, as well as config pulls from items in the root hierarchy like screen brightness ( I will eventually regain my geo-fencing which I lost with my Lyrics).  

I do see the config.json & config.xml files with the data I want.  I also see the hierarchy you mention above, can you make the final link to .... how do I state the REST or html request for currentActivity?
  
(I do understand that I need to do more learning on JSON ; in my 47yrs has not been something needed beyond basic awareness until now.  I promise to learn - this project is my incentive.)

For interest I have two systems (not zones) with two Infinity Touches ; so will have two pi's connected to each to gain the 485 conversation.  I have one hooked up with your recommended usb->485.  Its talking with cardump for a while then dumps with a "fatal error: Not trying again".  I suspect either my communications wire is inadequate or the old piB I had lying around bogs down and overruns the buffer.  I will try swapping out both one at a time (feel free to add hints here).

Again thanks for the fun you have provided here.  I appreciate your willingness to respond & respect the many hours you have invested in this project.  Cheers.

**Comment by sejgit** [comment]
sorry fat fingered the close

**Comment by nebulous** [comment]
>  I suspect either my communications wire is inadequate or the old piB I had lying around bogs down and overruns the buffer. I will try swapping out both one at a time (feel free to add hints here).

Any pi has _far_ more than enough horsepower to keep up with the serial stream, so I would look at wiring first. In my case I initially used some jumper wires which did not work reliably. Ended up switching to a section of the same solid thermostat wire that the rest of the system used: http://i.imgur.com/ZObXc99.jpg

> I do see the config.json & config.xml files with the data I want. I also see the hierarchy you mention above, can you make the final link to .... how do I state the REST or html request for currentActivity?

There isn't presently a built-in way to get only a single variable from status, but it's trivial to do so on the commandline on the pi, or with YourFavoriteProgrammingLanguage's JSON or XML library. What language is used to write scripts on the ISY994i? Can it parse json or xml?

**Comment by sejgit** [comment]
Thanks for the response,
I will keep investigating the wiring. I have shortened the cables to about the shortest without putting inside the furnace & tried to match the gauge using twisted pair. Like you suggest I will try to dig up something shielded matching what the installers used. 
Like many home automation devices the ISY has its quirks. Less a language than each program is in an if-then-else format. You can send and receive http using variables.  It also has a REST interface. 
Boy I tried every combo trying to get my one variable out of the Infinitude interface. Got frustrated. Looks like a even set a few ghost variables in the process. Lol. 
So, I have been studying JSON & have found some of the processing tools you mention. 
I will likely write a small python program on the pi to process and then flag the ISY through its rest interface by changing a variable. Say 1 for home, 2 for away, etc. Then I can use that inside the ISY for feedback. We will see what kind of lag I get from settings to feedback. 
So again, thanks for taking the time and giving the hints. The new approach should work. 
I will let you know how the two issues of 485 & ISY communication work out.

**Comment by sejgit** [comment]
One more thought ; you had mentioned wanting to add aggressive resetting of the 485 communications & also that sometimes that you needed to jump start using carddump.  Is there a reset of the line I could add either in Infinitude or external?  I will still pursue the long term fix of less noisy communications.  Thanks again ; this is fun stuff.

**Comment by sejgit** [comment]
Just an update, wrote a python program to sit on the pi and act as the go between the ISY994i & Infinitude.  As a bonus it updates my phone through prowl of changes or temps out of range.
Means I can push away, or home through the phone using the same interface I do all my home automation.
Also provides the geofencing for automated coming and going of my wife & I.
Its over at sejgit/furnace if anyone is interested.  I know my case is very specific but might be useful to someone out there.
Final step might be to take the two servers and put them on one pi (I have two furnaces).  Currently using two Pi 1Bs , would use one Pi3.  Just to clean it up ; will need to run two instances of Infinitude and my python program.  Not using the 485 network ; have sent them to /dev/null  

Thanks again for providing this link to the Carrier system Nebulous!  Much appreciated!!!!!
