### ISSUE TITLE
MOJO EMIT error.

### ISSUE THREAD

**Issue by ehwest** [nebulous/infinitude#33]
Using 
JBtek USB to RS485 Converter Adapter ch340T chip 64-bit Window 7 Supported on a Raspberian Pi per instructions.
The instructions seem to omit the necessary sudo here:

./infinitude daemon -m production -l http://192.168.1.232:80

However, I do this now:

sudo ./infinitude daemon -m production -l http://192.168.1.232:80
and get errors as follows;

pi@raspberrypi:~/infinitude$ sudo ./infinitude daemon -m production -l http://192.168.1.136:80
Using /dev/ttyAMA0 serial interface
[Sat Feb 25 19:12:21 2017] [info] Listening at "http://192.168.1.136:80"
Server available at http://192.168.1.136:80

Then everything is quiet.  So when I point a browser at this address, I get this
15
![img_1695](https://cloud.githubusercontent.com/assets/1304844/23336081/2538ec6c-fb92-11e6-9341-b13448043b28.JPG)
 seconds later:   

Mojo::Reactor::EV: Timer failed: Can't call method "emit" on an undefined value at /usr/local/share/perl/5.20.2/Mojo/IOLoop/Stream.pm line 72.
Mojo::Reactor::EV: Timer failed: Can't use an undefined value as a symbol reference at /usr/local/share/perl/5.20.2/Mojo/Reactor/EV.pm line 34.

Where do I look to address this?
Also, the instructions say to set the proxy on the thermostat.   Its unclear whether this should be the same port as the GUI  (80).

![img_1694](https://cloud.githubusercontent.com/assets/1304844/23336013/91c95df0-fb90-11e6-8dc9-1f76367dedbd.JPG)

pi@raspberrypi:/dev$ ls -tl |head
I'm guessing that there is some stream that ins't getting connected....maybe a bad AMA0 device....on the other hand, it is clear the raspberry pi interface comes up as expected....

crw-rw-rw- 1 root tty       5,   2 Feb 25 19:31 ptmx
prw-r----- 1 root adm            0 Feb 25 19:30 xconsole
crw--w---- 1 root tty     204,  64 Feb 25 19:18 ttyAMA0
crw--w---- 1 root tty       4,   1 Feb 25 19:18 tty1
drwxr-xr-x 2 root root        2460 Feb 25 19:18 char
drwxr-xr-x 4 root root          80 Feb 25 19:18 serial
crw-rw---- 1 root dialout 188,   0 Feb 25 19:18 ttyUSB0
crw--w---- 1 root tty       4,   5 Feb 25 19:18 tty5
crw--w---- 1 root tty       4,   6 Feb 25 19:18 tty6

**Comment by nebulous** [comment]
The proxy server should be the same ip and port as the gui, so in your case that's port 80. When the thermostat starts talking to infinitude the little globe at the top will turn from red to blue.

As for your serial device are you sure it's ttyACM0? I would guess that's the pi's serial console and that you might really want to use ttyUSB0.

**Comment by sejgit** [comment]
If it helps.  The instructions on the Pi kind of merged the regular and the UART so I did a redo on the ttyAMA0 going back to the ttyUSB0.  yes. yes. I should read more carefully.  Anyway, the ttyUSB0 with the same IP:Port worked well for me ; I am still struggling with the communications shutting down after a bit, but am pursuing wiring issues first.

**Comment by ehwest** [comment]
Thanks!
ok, yes, it should be ttyUSB0, based on simply pluggin and unplugging the adapter and noticing ttyUSB0 appears and disappears from the folder /dev/tty*    I'll submit some instructions to check this on the installation guide.

I'll check using cardump now.

No errors unless HTTP GET on port 80 is pulled, then I get this:

pi@raspberrypi:~/infinitude$ sudo ./infinitude daemon -m production -l http://192.168.1.136:80
Using /dev/ttyUSB0 serial interface
[Sun Feb 26 21:04:23 2017] [info] Listening at "http://192.168.1.136:80"
Server available at http://192.168.1.136:80

Mojo::Reactor::EV: I/O watcher failed: Can't use an undefined value as a symbol reference at /usr/local/share/perl/5.20.2/Mojo/Reactor/EV.pm line 34.
