### ISSUE TITLE
setting profiles dynamically. 

### ISSUE THREAD

**Issue by 7ooL** [nebulous/infinitude#35]
My house can already do a number of things when different trigger events occur. I'm working on dynamically setting the hvac profiles based on events such as arriving/leaving the home.

outside of the infinity's preprogrammed schedule I can set profiles using the HOLD UNTIL commands to adjust for fluctuations in schedules. for example:
`'http://192.168.1.248:3000/api/1/hold?activity=away&until="16:45"`
how can i set UNTIL to the "per schedule" option to cancel a current hold?

**Comment by 7ooL** [comment]
i was able to figure it out `http://192.168.1.248:3000/api/1/hold?hold=off`

**Comment by 7ooL** [comment]
any idea when you will move to a rest api?

**Comment by nebulous** [comment]
Can you define what you mean by rest? Presently the api is a superset of rest, being very promiscuous with http action types, but it _will_ respond to PUT requests for settings for instance. As far as when I'll have the time to make the api "more betterer" that's likely to be a while as I have a newborn eating my time/money/sanity.

**Comment by 7ooL** [comment]
no worries about this issue any more. I have been able to figure out how to set the profiles the way i wanted to using GET.
