### ISSUE TITLE
Vacation editor

### ISSUE THREAD

**Issue by 7ooL** [nebulous/infinitude#38]
This is going to be the next thing i would like to get working on my project. I don't use the infinitude interface but rather just its ability to pull and push data to the HVAC system. Its a shame Carrier doesn't expose an api.

The project i am working on is a complete home automation system. That works with a number of python scripts, IFTTT triggers, Alexa commands and web interface buttons.

Right now, using geo-loaction via my iphone the house "knows" if im home or away. and i use the GET commands to update the HVAC profile accordingly to adjust for fluctuations in my schedule. I have what is known as a "VACATION" mode that automates the lights in the house when im away (25 Hues bulbs). All that i would need in the infinitude vacation implementation is the ability to push an end datetime to HVAC system. something similar to hod the activity hold current works. i'm thinking something like
`'http://192.168.1.248:3000/api/1/hold?activity=vacation&until="2017-03-31T19:26:18Z"`

i'd be willing to work on it if you can get me started.

My project's interface.
![image](https://cloud.githubusercontent.com/assets/11856305/23445600/7dabbc74-fe0a-11e6-81c2-bc219be8780f.png)

**Comment by ehwest** [comment]
The vacation data for non-touch systems is readily available.  attached is the protocol.
[carrier_code_table.docx](https://github.com/nebulous/infinitude/files/823266/carrier_code_table.docx)

**Comment by chucky843** [comment]
Im an hvac technician, just had our carrier spring update class today, found out that they will offer api access for home automation purposes for a FEE i will get info and share

**Comment by 7ooL** [comment]
@chucky843 any news on it?

**Comment by 7ooL** [comment]
at the very least i'd like to be bale to use something similar to the other hold commands: `http://192.168.1.248:3000/api/1/hold?activity=vacation&until=19:45`

**Comment by chucky843** [comment]
[Infinity-Evolution Open API - Getting Started - v1.pdf](https://github.com/nebulous/infinitude/files/903390/Infinity-Evolution.Open.API.-.Getting.Started.-.v1.pdf)

Here is what I was able to dig up on the subject, sorry for the 8 day delay, I been pretty busy with work.

Hope this helps

**Comment by randellhodges** [comment]
@chucky843  Nice, but the documentation has a Sept 2016 date in it and none of the links with openapi work and here it is April 2017. Not very open if they plan on selling access.

This isn't directed at you.

This is the kind of thing that'll make me look elsewhere in the future. 

There should be a local API on the thermostat that we can connect to without oauth or anything like that. If I want access to a cloud api, then at the *most* it should be a 1 time fee (and really, I think I already paid that one time fee when I bought the expensive system).

**Comment by nebulous** [comment]
What @randellhodges said. ⏫ 

A vacation editor is on my lengthy todo list, but unfortunately spare time to work on it is not presently! 🙁

**Comment by 7ooL** [comment]
i'd like to bump this to do. perhaps if you could point me topo where i need to configure it in the files i could branch off a build. It would be a learning curve for me.

**Comment by nebulous** [comment]
vacation editor added ~in develop branch~ to master
