### ISSUE TITLE
Adding Bryant Support

### ISSUE THREAD

**Issue by amunter-nist** [nebulous/infinitude#4]
Looks like a bunch of addresses in xml files in the defs directory need to be changed to api.eng.bryant.com?  Also I have an FE4AF005 fan coil which is also a carrier part number, so maybe the same address as the one you used?  My heat pump is a 288BNV037 which is the same as Carrier part number 25VNA837.  Once I get the RS485 I can watch for the traffic, I think, and see the addresses.

**Comment by nebulous** [comment]
Hopefully I can clear some of this up...

Infinitude gets information from at least one, and optionally two places. You do *not* need an RS485 adapter to use infinitude if you have a network-connected thermostat. An RS485 adapter makes additional information available, however, and we hope to be able to control non-network-enabled thermostats via RS485 in the future.

The defs directory is purely informational. No infinitude code actually uses those files. That said, is your thermostat trying to contact api.eng.bryant.com? If so, and if it uses the same endpoints as the carrier models, we should be able to tweak the ```before_dispatch``` sub to intercept bryant as well as carrier queries. You might experiment with this by altering line ~51 of infinitude ```if ($url->to_abs->host =~ /carrier/) {``` to be ```if ($url->to_abs->host =~ /(carrier|bryant)/) {```

Glad to have you on the project, and let me know if I can help further.

**Comment by amunter-nist** [comment]
Got it, thanks.  I have my pi at work at the moment.  I'll bring it home and plug it in at the router for now and make the change you suggest to see if it works after setting the proxy.  Then if the proxy works I'll put the adapter in when it arrives and see what else I can see.

**Comment by amunter-nist** [comment]
I finally got around to working on this.  When I added the "or" statement you suggested in the regex it works, locally at least.  It does seem to stop updating the Bryant website and it doesn't seem to be accepting commands from the https://www.myevolutionconnex.bryant.com/ page even though that website think it is sending commands.  Any suggestion for getting that to work?

I can see the top row of gauges without the RS485 connected.  Can also see profiles and schedules.  I put in a wunderground API key, but am not sure how this is used in the code yet.  I'll see about hooking up the RS485 now that it's partially working and see if I can get that data in as well.

**Comment by nebulous** [comment]
I must admit I don't actually use the Carrier apps, so the passthru hasn't received much attention. Can you elaborate a bit more as to what works and what doesn't?

1) changing settings in infinitude changes them on thermostat
2) changing settings on thermostat updates infinitude
3) changing settings in Carrier/Bryant web page changes them on infinitude/thermostat
4) changing settings on thermostat updates infinitude/Carrier/Bryant webpage

**Comment by amunter-nist** [comment]
I'll test it out and get back to you.  Is serial port support required in
order for changes in infinitude to change them on the thermostat?

**Comment by nebulous** [comment]
Serial is not required for any settings changes in Infinitude. All settings are accessed and changed via http. Presently serial is exclusively a Read Only and completely optional feature.
