### ISSUE TITLE
Wiki instructions did not work for Rasbian Strech (Solved)

### ISSUE THREAD

**Issue by GitBeagle** [nebulous/infinitude#44]
My Infinitude Raspberry pi stopped working after a power outage.  It had been working great for almost a year. In the meantime I had forgotten the password. Dumb!  Anyway I started over with the current version of Rasbian Stretch lite.  After much trial and error I got Infinitude working using the following steps. YMMV!

I followed the instructions for the Raspberry pi in the wiki but ran into problems. The Weather Underground module didn't install correctly.  It complained about needing inc::Module::Install, etc. While not a complete Linux noob this was beyond me.

After a bit of Googling I read about possible compiler incompatibilities.  Not sure it was necessary but I installed gcc 4.7

	sudo apt-get install gcc-4.7

No luck I still got the same error.   More Googling lead me to install Module::Install since that is what it said it was missing. (sudo probably not required)

	sudo cpanm -S inc::Module::Install

Then it said it was missing JSON so I installed it using the following.
	
	sudo cpanm install JSON
	
Finally I was able to install Weather Underground without errors.  IO::Termios had already installed without errors.

	sudo cpanm -S WWW::Wunderground::API 

After all this Infinitude started without errors.

I'm not suggesting you use Rasbian Strech but if you do I suspect this might be helpful...

John

**Comment by nebulous** [comment]
Thanks for the detailed report! I don't run Infinitude on a rpi, so I rely on others to keep the wiki updated. Feel free to edit as appropriate!
