### ISSUE TITLE
Status Screen reports: {{ notifications.notification[0].message[0] }} {{ notifications.notification[0].timestamp[0] | date:"EEE yyyy-MM-dd 'at' h:mma" }}

### ISSUE THREAD

**Issue by rcojoe** [nebulous/infinitude#45]
I have data flowing.  The serial looks correct, and I see my fan coil, my thermostat, and something that the project is needing some data from, a device id 128, which is a NIM on my geothermal dumb unit.  

What I expect to see:
 I would see temp and humidity at least since I have that data on my thermostat.

What I am seeing instead:
The humidity gauge looks like it defaults on the status screen to show up when I don't have a the serial hooked up.  But with the message above, there are no gauges showing.  Just this error message.

I have a non wifi older black and white infinity non touch thermostat.
Thanks

Joe

**Comment by nebulous** [comment]
I should preface this by stressing again that Infinitude was _not_ designed to work with non-touch, non-internet connected thermostats. For that I would recommend @acd's excellent Infinitive project.

The humidity gauge uses the humidity variable reported from the thermostat via webservice by default(which you wouldn't have available), but upgrades to the more quickly-refreshed serial version of the same data when it detects a serial stream. Unfortunately there is _very_ little consistency between devices as to where they report values, so yours is likely reporting in a different place than others we have mapped. But good news! This is what the serial monitor was in fact designed for: inspecting the serial stream and identifying pertinent data. So if you report the register and offset of temp/humidity data, I'll integrate it into future versions of Infinitude.

**Comment by rcojoe** [comment]
Nebulous.  Thank you for the feedback.  I have used infinitive and liked it, and it does serve the purpose I was needing, which was to control my thermostat temp.  I enjoyed your software, which was my first to hook to my network,  and I'll see if time permits me to dive into this and map the humidity as well as other values.  Thanks for your time on this project.
