### ISSUE TITLE
Can't find bower_components?

### ISSUE THREAD

**Issue by watkipet** [nebulous/infinitude#48]
I followed the Wiki steps for installing on a raspberry PI. However, when I navigate the server with a web browser, most of the UI components fail to load. There are lot of loading errors from 'bower_components'. That directory doesn't seem to be present in the 'public' directory. Am I missing a dependency or build step?

**Comment by nebulous** [comment]
Unless you've made changes to the frontend code and need to rebuild (see `grunt build` in the public dir in that case), then you should be able to run infinitude in production mode, which will use the statically compiled frontend assets in the `dist` dir. Try either adding the `-m production` flag or set the `MOJO_MODE` environment variable to `production`

**Comment by nebulous** [comment]
I committed a change 7ef4e962c5be which should more aggressively default to production rather than development mode.  Hopefully that helps and thanks for the feedback.

**Comment by watkipet** [comment]
That fixed it. Thanks!
