### ISSUE TITLE
Display multiple zones on main page.

### ISSUE THREAD

**Issue by scyto** [nebulous/infinitude#5]
Show multiple zones on home page, not sure how it picks the zone to show?

I have three zones would be good to see the details for each.

**Comment by nebulous** [comment]
Presently it displays zones "naively" aka "stupidly." :) Thanks for opening an issue. It will give us a way to track changes without adding noise to general discussion thread. If you send me your systems.json and status.json file I'll use them for testing.

**Comment by nebulous** [comment]
I believe this will show gauges for all enabled zones on the main page. Can't be certain since I don't have a multi-zone system.

**Comment by scyto** [comment]
ahh i see the main issues page doesn't show closed ones, do you want me to email the json files?

**Comment by scyto** [comment]
umm ok, i am stupid, where do i find the json files?

**Comment by scyto** [comment]
oh i am dumbass - you are saying the commit a66a4bb will now show the zones - ok, will pull down the latest

**Comment by scyto** [comment]
Yes it does show the enabled zones on the main page here is a shot (any idea on the font size issue?)

<img width="1285" alt="2016-02-02 1" src="https://cloud.githubusercontent.com/assets/11369180/12771214/61fd26b0-c9dc-11e5-8aa0-fd3f9ace9c69.png">
