### ISSUE TITLE
Multiple Carrier Units

### ISSUE THREAD

**Issue by jgyates** [nebulous/infinitude#51]
Does Infinitude support multiple thermostats (i.e. multiple HVAC units). It appears to only support one for a given instance of infinitude, or am I missing something. It is working with multiple zones within a single touch thermostat, but my use case is multiple touch screen thermostats, each with multiple zones.

If I enable both the result I get are thermostat 1 shows up on the status page, but thermostat 2 zones show up on the comfort profile and schedule page.

**Comment by nebulous** [comment]
If you have genuinely separate sets of systems the simplest way to handle that would be to run multiple instances of infinitude on different ports with different database folders. If multiple stats connect to the same infinitude server, they'll write over each others data and make a general mess as it seems you've discovered 🙂

**Comment by sejgit** [comment]
I will confirm that running two instances on one server (Pi3 in my case) works very well & reasonably simple to run.  I cloned into two separate directories then hold my systemd files in another GitHub repository.  take a look at GitHub.com/sejgit/furnace for that one.  I run one on port 81 & the other furnace on 82.  Been running for more than a year this way.  Thanks to nebulous!
