### ISSUE TITLE
Getting stream and state data but no status

### ISSUE THREAD

**Issue by mattster98** [nebulous/infinitude#53]
When I visit the status page I get this in the console.  Raspi running Raspbian Stretch

Mojo::Reactor::EV: I/O watcher failed: Can't use an undefined value as a symbol reference at /usr/share/perl5/Mojo/Reactor/EV.pm line 34.

Gui shows only global humidity and it's all gray.

**Comment by mattster98** [comment]
![image](https://user-images.githubusercontent.com/1469426/44007743-ce3baafa-9e68-11e8-9a7a-009e9d904c4b.png)

Was thinking it wasn't working at all anymore, but got a screencap of the state I've seen.

Also got these errors (below) starting up most recently (don't recall seeing them before).  Will investigate those separately.

====
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LC_CTYPE = "en_US.UTF-8",
        LANG = "en_US"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US").

**Comment by nebulous** [comment]
It may be that you need to reset your serial device's tty settings. Assuming it's ttyUSB0, try: `stty -F /dev/ttyUSB0 -brkint -icrnl -imaxbel -opost -isig -icanon -iexten -echo` and restart infinitude. The last screenshot you sent appears to be junk data that just so happens to checksum correctly.

**Comment by nebulous** [comment]
Also see [cardump](https://github.com/nebulous/infinitude/tree/master/contrib/cardump) to test the serial connection(which incidentally will also reset the serial tty consistent with the settings above) independent of Infinitude.

**Comment by mattster98** [comment]
Attaching some cardump output in case I'm running an unsupported system or something newer that needs some tweaks.
[cardump.txt](https://github.com/nebulous/infinitude/files/2282942/cardump.txt)

**Comment by mattster98** [comment]
Aaand, I'm finally getting up to speed.  I went off the rails to the RasPi setup and missed the part where you point the touch thermostat to it. :)  I thought it got everything from the RS485.  That's probably why I don't have status?

**Comment by nebulous** [comment]
>Aaand, I'm finally getting up to speed. I went off the rails to the RasPi setup and missed the part where you point the touch thermostat to it. :) I thought it got everything from the RS485. That's probably why I don't have status?

ah yes, quite. Infinitude is designed to replace Carrier's cloud-based webservice with a local version. It does so on the wifi touch thermostats running v12 firmware, though it may also work on newer firmwares as well. The RS485 aspect is purely readonly and is there to help others watch their bus and possibly gain insight into reverse engineering it. If you want to control your stat via rs485(and have the older non-wifi thermostat) you'll want to try out the Infinitive project (acd/Infinitive)

**Comment by mattster98** [comment]
Thanks for the patient noob help.  Got the proxy set up but now only seeing humidity on the status screen.  Will open a new issue if you like.

**Comment by mattster98** [comment]
Ok.. just ignore me.  Good now.  I'm slowly backing away while this works. :)
