### ISSUE TITLE
missing item in cpanfile

### ISSUE THREAD

**Issue by umdhollings** [nebulous/infinitude#68]
There is one missing package in the CPAN file XML::Simple.   Here is a diff to add it.

index 9b807f1..84109bb 100644
--- a/cpanfile
+++ b/cpanfile
@@ -5,6 +5,7 @@ requires 'Try::Tiny';
 requires 'Path::Tiny';
 requires 'JSON';
 requires 'Hash::AsObject';
+requires 'XML::Simple';
 
 suggests 'WWW::Wunderground::API';
 suggests 'IO::Termios';

**Comment by nebulous** [comment]
fixed in 99abaed608d
