### ISSUE TITLE
Use infinitude on Carrier Comfort zone II

### ISSUE THREAD

**Issue by kpschaper** [nebulous/infinitude#7]
Hello,  I noticed that you currently only support wireless thermostats and use rs485 to get additional information.

I was wondering how much work it would be to support this system:
http://www.strongsvilleheating.com/images/company_assets/170AC653-CD77-4E14-831B-74F4694F5585/zonekit4zcar_03fe.PDF

I have the four zone system.
Thanks!

**Comment by nebulous** [comment]
That appears to use the same rs485 communications bus as other Carrier/Bryant devices. If the register locations can be reverse engineered, then Infinitude(or any other software) could control it, yes. Depending on what type of thermostat you have controlling the whole network though, that thermostat may fight with other controllers.

Infinitude _can_ help you do that reverse engineering of register locations though. If you get it running with a rs485 adaptor, Infinitude will display a running stream of parsed frames on the serial bus, and indicate which values are changing over time. By making small changes and watching the result on the serial bus, values can be identified.
