### ISSUE TITLE
Changing Server IP

### ISSUE THREAD

**Issue by Bchap9** [nebulous/infinitude#71]
I am trying to set up (mostly) full home automation, I saw this project as one of the final touches, and I love the idea. I have set up the server on a rpi, but am unable to connect my thermostat to the server at any port. It is a SYSTXCCLTC01-A, and when i attemp to save the change of the server address, is just reverts back to www.api.ing.carrier.com. Anyone had this issue? Anyone have a solution.

**Comment by nebulous** [comment]
You don't want to change the server address, you want to add Infinitude as a _proxy_.

(Thermostat)->(Infinitude)->(Carrier)
