### ISSUE TITLE
As well as providing an open RESTful api and monitoring of weather and any other sensors you may want to integrate.

### ISSUE THREAD

**Issue by kskenyon** [nebulous/infinitude#74]
Do you have instructions on how to use this new RESTful api for sensor data?

**Comment by bdf0506** [comment]
It really depends on your platform....what are you trying to do? I believe the help context was put there as a general statement, since it is an API, it pulls JSON data and you can integrate it easily within other applications.

**Comment by kskenyon** [comment]
Got it, I’ve already been doing that for a while through Node Red.  I though the update meant something new had been added.  

Kevin
