### ISSUE TITLE
docker-compose on RPi

### ISSUE THREAD

**Issue by zachsteffens** [nebulous/infinitude#76]
I'm having some issues getting this up and running on a rpi using docker.  
building the dockerfile I end up with the error 
`COPY failed: stat /var/lib/docker/tmp/docker-builder569210230/entrypoint.sh: no such file or directory`

using docker-compose up -d I end up with the error 
`ERROR: Cannot locate specified Dockerfile: Dockerfile`

Is there a different image I need to pull to get it running on a rpi?

**Comment by Coch** [comment]
I didn't pull a different image but here's my dockerfile -- I believe I ended up having to manually copy entrypoint.sh into the image (I remember having lots of fun with this...)

`# We're going to see if we can somehow make this work on debian:stretch instead of jessie
#FROM ubuntu:latest
FROM debian:stretch

RUN apt-get update && apt-get -y upgrade \
        && apt-get install -y git build-essential cpanminus libchi-perl libmojolicious-perl libdatetime-perl libxml-simple-perl libmoo-perl libjson-maybexs-perl libhash-as
object-perl libdata-parsebinary-perl libdigest-crc-perl libcache-perl libtest-longstring-perl libio-pty-perl \
        && git clone https://github.com/nebulous/infinitude.git /infinitude \
    && chmod +x /infinitude/infinitude \
    && cd /infinitude \
    && cpanm Mojolicious::Lite CHI DateTime Try::Tiny Path::Tiny JSON IO::Termios inc::Module::Install \
    && cpanm --force  WWW::Wunderground::API
COPY ./entrypoint.sh /
EXPOSE 3000
ENTRYPOINT /entrypoint.sh
`

**Comment by bdf0506** [comment]
@Coch post was helpful as a starting point, but the formatting made it hard to fully understand.

I manually created this docker file, and this worked for me. I don't know docker all that well, so I stumbled through and did the following to get it to work on a Raspberry Pi. Perhaps I am not using docker best practices, if anyone has a better way to run this, please let me know. @MizterB any input?

The entrypoint path was wrong as well, so notice that I modified this. The Wunderground API is dead, so those lines likely aren't needed anymore.

```
FROM debian:stretch

RUN apt-get update && apt-get -y upgrade \
        && apt-get install -y git build-essential cpanminus libchi-perl libmojolicious-perl libdatetime-perl libxml-simple-perl libmoo-perl libjson-maybexs-perl libhash-asobject-perl libdata-parsebinary-perl libdigest-crc-perl libcache-perl libtest-longstring-perl libio-pty-perl \
        && git clone https://github.com/nebulous/infinitude.git /infinitude \
    && chmod +x /infinitude/infinitude \
    && cd /infinitude \
    && cpanm Mojolicious::Lite CHI DateTime Try::Tiny Path::Tiny JSON IO::Termios inc::Module::Install \
    && cpanm --force WWW::Wunderground::API
EXPOSE 3000
ENTRYPOINT /infinitude/docker/entrypoint.sh
```

Use the following to build the image:
```docker build -t infinitude -f /tmp/DockerFile .```

To run it:
```docker run -dit --restart unless-stopped -p 3000:3000 --name infinitude infinitude ```
