### ISSUE TITLE
Small issue with displays of multiple zone info on main page

### ISSUE THREAD

**Issue by c0t0d0s2** [nebulous/infinitude#78]
While the app shows dials perfectly for multiple zones, the info box seems to get a bit confused, at least with my setup.  Screenshot attached.
<img width="1063" alt="infinitude-screenshot" src="https://user-images.githubusercontent.com/159020/58815496-51585e80-85ed-11e9-83ba-4894c19edfed.png">

It's a Bryant system, fyi:
Thermostat: systxbbecc01-B, software version 131626-02.00
Zone board: systxbb4zc01
AC Model 189bnv(060000FA Evolution® Variable-Speed Air Conditioner
Model)
Fan Coil: FE4ANB006
(if it matters, but hey, why not?)

If you need data to help test a setup like mine, I'm OK with providing data.

**Comment by bdf0506** [comment]
What are you expecting to see? This really isn't much different than my single zoned system. I think maybe you are referring to the zones, which in this case seems to be just a dump of the api in that field - a variation of the following api call is placed there: `http://hassio.home:8080/api/status`

![image](https://user-images.githubusercontent.com/5414343/58819401-232f4a80-85fe-11e9-90a5-1c694fc12fce.png)

**Comment by c0t0d0s2** [comment]
Ahh, ok.  My bad, I had assumed that was just a bug from having a multizoned system.  If it was, I wondered if I could send any data; but it appears its by design.

Sorry to bug you and THANKS!  I love the software.
