### ISSUE TITLE
Control "Away" Status via infinitude

### ISSUE THREAD

**Issue by adorsett** [nebulous/infinitude#8]
The SAM has a command for setting a zone unoccupied to change from Home to Away. Can this functionality be added to infinitude so that I can change home/away status via Google calendar?  Thanks!

**Comment by nebulous** [comment]
I believe this is already supported. `/api/<yourZoneId>/hold?activity=away`

**Comment by adorsett** [comment]
Thanks!  I couldn't find a spec for the infinitude API, thus why I asked. Can you put a link on the main wiki?
