### ISSUE TITLE
No MYMETA file is found after configure. You toolchain is too old?

### ISSUE THREAD

**Issue by rab523** [nebulous/infinitude#80]
First, I must confess that I know little to nothing about Perl or even programming, but I have been growing in familiarity with Github through my interest in Homebridge.

I am using a Mac mini to install Infinitude. I am on the ./infinitude daemon command and am getting this result...

> The resulting feedback I get in the Terminal is as follows....
--> Working on .
Configuring /Users/me ... N/A
! No MYMETA file is found after configure. Your toolchain is too old?
! Configuring . failed. See /Users/me/.cpanm/work/1573940787.6912/build.log for details.
My-Mac-mini:~ me$ sudo cpanm --installdeps
Usage: cpanm [options] Module [...]

>Try `cpanm --help` or `man cpanm` for more options.
My-Mac-mini:~ me$ 

Wondering what my next step should be. I am running Perl 5.18.4 on macOS Mojave 10.14.6.

**Comment by nebulous** [comment]
There appear to be a few good troubleshooting tips in [your reddit thread](https://www.reddit.com/r/perl/comments/dxqrj0/help_with_perl_to_use_thermostat_with_homekit/) about this. Did you get any further with this? Also, `./infinitude daemon` shouldn't be run until dependencies are installed. https://github.com/nebulous/infinitude#installation

**Comment by nebulous** [comment]
Hopefully the lack of reply means you've addressed the dependency installation issues. Feel free to re-open this ticket if you have further questions.
