### ISSUE TITLE
Temperature format

### ISSUE THREAD

**Issue by compil3** [nebulous/infinitude#82]
Is there a way to change it from F to C?  I don't see an option nor can I find anything on how to.

**Comment by jbrockerville** [comment]
I too would like this. Is the `cfgem` field units? I'm in C and its value is 'C'. Just a guess. Also, it would appear that the 'Outside' temperature, the `oat` field, is reported in F despite the tstat being in C. All the other reported temps are good and in C. Odd.

**Comment by nebulous** [comment]
cfgem is indeed the thermostat's setting for F/C. As a backward imperialist I never tested metric units. The values in Infinitude come directly from the thermostat. I assumed since one can change the thermostat to C that the it would then return status in C. Are the values in status returning in F? I can certainly make an option to convert the units, but it seems like something that should be doable in the 'stat itself. 🤔

**Comment by jbrockerville** [comment]
As a silly metricist, I had to change the units from the factory default. I just changed the units to F and back to C, checking the Infinitude values each time, so I can confirm that, yes, the tstat does do all the conversion for you except `oat`, aka outside temp. It's weird. The tstat shows `oat` in C on the tstat display, but sends F in the json.

**Comment by jbrockerville** [comment]
Locally, to show C for `oat`, I did `{{((status.oat[0] - 32) * 5/9).toFixed(1)}} &deg;{{status.cfgem[0]}}`. But that hardcodes C for me. You could `ng-if` the element I guess. I was lazy.

**Comment by nebulous** [comment]
Weird. Do you have a serial adaptor connected to infinitude, or just wifi? If you're getting data from serial as well as wifi, then it might be my bug(since I believe the serial bus is in F no matter what).

**Comment by jbrockerville** [comment]
Nope. No serial. I didn't need that much control or detail.

**Comment by sarahmva** [comment]
Here is my Zone date (also Centigrade System). All internal temps report correct in C, the oat is reporting in Ffrom the system... Not very logical.

{"zone":[{"fan":["off"],"name":["ZONE 1"],"rt":["26.0"],"hold":["off"],"id":"1","enabled":["on"],"clsp":["26.0"],"currentActivity":["home"],"htsp":["21.5"],"damperposition":["15"],"zoneconditioning":["active_cool"],"otmr":[{}],"rh":["39"]},{"htsp":["15.5"],"clsp":["26.5"],"currentActivity":["away"],"id":"2","enabled":["off"],"fan":["off"],"name":["Zone 2"],"hold":["off"],"rt":[{}],"rh":["39"],"otmr":[{}],"zoneconditioning":["active_cool"],"damperposition":["15"]},{"zoneconditioning":["active_cool"],"damperposition":["15"],"rh":["39"],"otmr":[{}],"enabled":["off"],"id":"3","hold":["off"],"rt":[{}],"fan":["off"],"name":["Zone 3"],"htsp":["15.5"],"currentActivity":["away"],"clsp":["26.5"]},{"hold":["off"],"rt":[{}],"name":["Zone 4"],"fan":["off"],"enabled":["off"],"id":"4","currentActivity":["away"],"clsp":["26.5"],"htsp":["15.5"],"damperposition":["15"],"zoneconditioning":["active_cool"],"otmr":[{}],"rh":["39"]},{"currentActivity":["away"],"clsp":["26.5"],"htsp":["15.5"],"hold":["off"],"rt":[{}],"name":["Zone 5"],"fan":["off"],"enabled":["off"],"id":"5","otmr":[{}],"rh":["39"],"damperposition":["15"],"zoneconditioning":["active_cool"]},{"zoneconditioning":["active_cool"],"damperposition":["15"],"rh":["39"],"otmr":[{}],"enabled":["off"],"id":"6","rt":[{}],"hold":["off"],"fan":["off"],"name":["Zone 6"],"htsp":["15.5"],"currentActivity":["away"],"clsp":["26.5"]},{"zoneconditioning":["active_cool"],"damperposition":["15"],"rh":["39"],"otmr":[{}],"id":"7","enabled":["off"],"fan":["off"],"name":["Zone 7"],"hold":["off"],"rt":[{}],"htsp":["15.5"],"clsp":["26.5"],"currentActivity":["away"]},{"otmr":[{}],"rh":["39"],"damperposition":["15"],"zoneconditioning":["active_cool"],"currentActivity":["away"],"clsp":["26.5"],"htsp":["15.5"],"hold":["off"],"rt":[{}],"name":["Zone 8"],"fan":["off"],"enabled":["off"],"id":"8"}]}

**Comment by nebulous** [comment]
Can you attach the contents of `/status.json`?

**Comment by sarahmva** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<status version="1.7"><cfgem>C</cfgem><cfgtype>heatcool</cfgtype><filtrlvl>80</filtrlvl><humid>off</humid><humlvl>33</humlvl><localTime>2020-07-13T17:43:22-04:59</localTime><mode>cool</mode><oat>90</oat><oprstsmsg>idle</oprstsmsg><uvlvl>100</uvlvl><vacatrunning>off</vacatrunning><ventlvl>100</ventlvl><zones><zone id="1"><clsp>26.0</clsp><currentActivity>home</currentActivity><damperposition>15</damperposition><enabled>on</enabled><fan>off</fan><hold>on</hold><htsp>21.5</htsp><name>ZONE 1</name><otmr>22:30</otmr><rh>38</rh><rt>26.0</rt><zoneconditioning>active_cool</zoneconditioning></zone><zone id="2"><clsp>24.5</clsp><currentActivity>home</currentActivity><damperposition>15</damperposition><enabled>off</enabled><fan>off</fan><hold>off</hold><htsp>20.0</htsp><name>Zone 2</name><otmr/><rh>38</rh><rt/><zoneconditioning>active_cool</zoneconditioning></zone><zone id="3"><clsp>24.5</clsp><currentActivity>home</currentActivity><damperposition>15</damperposition><enabled>off</enabled><fan>off</fan><hold>off</hold><htsp>20.0</htsp><name>Zone 3</name><otmr/><rh>38</rh><rt/><zoneconditioning>active_cool</zoneconditioning></zone><zone id="4"><clsp>24.5</clsp><currentActivity>home</currentActivity><damperposition>15</damperposition><enabled>off</enabled><fan>off</fan><hold>off</hold><htsp>20.0</htsp><name>Zone 4</name><otmr/><rh>38</rh><rt/><zoneconditioning>active_cool</zoneconditioning></zone><zone id="5"><clsp>24.5</clsp><currentActivity>home</currentActivity><damperposition>15</damperposition><enabled>off</enabled><fan>off</fan><hold>off</hold><htsp>20.0</htsp><name>Zone 5</name><otmr/><rh>38</rh><rt/><zoneconditioning>active_cool</zoneconditioning></zone><zone id="6"><clsp>24.5</clsp><currentActivity>home</currentActivity><damperposition>15</damperposition><enabled>off</enabled><fan>off</fan><hold>off</hold><htsp>20.0</htsp><name>Zone 6</name><otmr/><rh>38</rh><rt/><zoneconditioning>active_cool</zoneconditioning></zone><zone id="7"><clsp>24.5</clsp><currentActivity>home</currentActivity><damperposition>15</damperposition><enabled>off</enabled><fan>off</fan><hold>off</hold><htsp>20.0</htsp><name>Zone 7</name><otmr/><rh>38</rh><rt/><zoneconditioning>active_cool</zoneconditioning></zone><zone id="8"><clsp>24.5</clsp><currentActivity>home</currentActivity><damperposition>15</damperposition><enabled>off</enabled><fan>off</fan><hold>off</hold><htsp>20.0</htsp><name>Zone 8</name><otmr/><rh>38</rh><rt/><zoneconditioning>active_cool</zoneconditioning></zone></zones></status>`

**Comment by sarahmva** [comment]
`{"status":[{"humid":["off"],"oprstsmsg":["idle"],"filtrlvl":["80"],"humlvl":["33"],"uvlvl":["100"],"cfgtype":["heatcool"],"cfgem":["C"],"localTime":["2020-07-13T17:52:00-04:59"],"oat":["90"],"zones":[{"zone":[{"name":["ZONE 1"],"fan":["off"],"rt":["26.0"],"hold":["on"],"id":"1","enabled":["on"],"clsp":["26.0"],"currentActivity":["home"],"htsp":["21.5"],"damperposition":["15"],"zoneconditioning":["active_cool"],"otmr":["22:30"],"rh":["38"]},{"clsp":["24.5"],"currentActivity":["home"],"htsp":["20.0"],"fan":["off"],"name":["Zone 2"],"hold":["off"],"rt":[{}],"id":"2","enabled":["off"],"otmr":[{}],"rh":["38"],"damperposition":["15"],"zoneconditioning":["active_cool"]},{"rt":[{}],"hold":["off"],"fan":["off"],"name":["Zone 3"],"enabled":["off"],"id":"3","currentActivity":["home"],"clsp":["24.5"],"htsp":["20.0"],"damperposition":["15"],"zoneconditioning":["active_cool"],"otmr":[{}],"rh":["38"]},{"hold":["off"],"rt":[{}],"fan":["off"],"name":["Zone 4"],"enabled":["off"],"id":"4","currentActivity":["home"],"clsp":["24.5"],"htsp":["20.0"],"damperposition":["15"],"zoneconditioning":["active_cool"],"otmr":[{}],"rh":["38"]},{"enabled":["off"],"id":"5","hold":["off"],"rt":[{}],"name":["Zone 5"],"fan":["off"],"htsp":["20.0"],"currentActivity":["home"],"clsp":["24.5"],"zoneconditioning":["active_cool"],"damperposition":["15"],"rh":["38"],"otmr":[{}]},{"htsp":["20.0"],"currentActivity":["home"],"clsp":["24.5"],"enabled":["off"],"id":"6","rt":[{}],"hold":["off"],"fan":["off"],"name":["Zone 6"],"rh":["38"],"otmr":[{}],"zoneconditioning":["active_cool"],"damperposition":["15"]},{"zoneconditioning":["active_cool"],"damperposition":["15"],"rh":["38"],"otmr":[{}],"id":"7","enabled":["off"],"fan":["off"],"name":["Zone 7"],"hold":["off"],"rt":[{}],"htsp":["20.0"],"clsp":["24.5"],"currentActivity":["home"]},{"rt":[{}],"hold":["off"],"fan":["off"],"name":["Zone 8"],"enabled":["off"],"id":"8","currentActivity":["home"],"clsp":["24.5"],"htsp":["20.0"],"damperposition":["15"],"zoneconditioning":["active_cool"],"otmr":[{}],"rh":["38"]}]}],"ventlvl":["100"],"mode":["cool"],"version":"1.7","vacatrunning":["off"]}]}`

**Comment by jbrockerville** [comment]
Same. `"cfgem":["C"]`, `"rt":["24.0"]` which is correct and in C, but `"oat":["71"]` which is correct but in F.

[status.json.txt](https://github.com/nebulous/infinitude/files/4916119/status.json.txt)

**Comment by sarahmva** [comment]
Awesome! Thank you so much :-)
