### ISSUE TITLE
hardware?

### ISSUE THREAD

**Issue by wayne5w** [nebulous/infinitude#86]
Hi, 

Just came across this site. Seems like a great project. I am not clear if I need any hardware beyond a Pi. There is a link in the readme for recommended hardware but that goes to Amazon with a page not found error/

**Comment by nebulous** [comment]
Thanks for the report. I updated the hardware links and added a few updates. The only requirements for Infinitude are:

1) a Carrier/Bryant touch thermostat
2) a device capable of running Linux(raspberry pi, desktop computer, pogoplug, Docker container, etc) on the same network.
