### ISSUE TITLE
Confirmation of requirements/status of README

### ISSUE THREAD

**Issue by dmdweiss** [nebulous/infinitude#87]
I am a newby learning python with Infinity thermostat. The README indicates a requirement to run on UNIX with Perl. Is this still true? Or can it now be used some other way for those of us on Windows?

The README also indicates: 
> With any luck, Carrier will allow the owners of these devices and data direct access rather than this ridiculous work around. If you have one of these thermostats, tell Carrier you'd like direct network access to your thermostat, or at the very least, access to a public API!
Is asking Carrier for an API out of date given that there is a public API, or I'm I not understanding? If its not out of date how do I lobby Carrier?  

When I contacted them previously they indiated they only took product requests from distributors.

(I'll post a separate issue about what I am looking to do that may be an enhancement request or simply a redirection. Thanks for all the work that has been done to get us more control!  I seem to be stuck with Carrier controller given my situation.)

**Comment by nebulous** [comment]
Infinitude is written in perl, and posix systems will be the simplest to run it in. If you must run it in Windows I would recommend running within a docker container. A Dockerfile is included in the repo.

Carrier does seem completely disinterested in serving end-users. Their business model has them working through middlemen for parts/service/allthethings. So I'm not holding my breath that they'll provide direct access to their api.

**Comment by swerb73** [comment]
I also successfully run it using strawberry perl on windows 10, then using npm to run it as a service.
