### ISSUE TITLE
Profiles page does not show what scheduled profile in in effect.

### ISSUE THREAD

**Issue by scyto** [nebulous/infinitude#9]
On the profiles page if zone 1 is set to hold and manual on the thermostat then the zone shows display on the profiles page shows hold = checked and the drop down manual and the until time.

For zone 2 and 3 they show nothing in these fields even though the zone is set as per schedule and i think the away profile.

**Comment by scyto** [comment]
More info and screenshot to show what i mean.
Also why does it say comfort profiles 2?  it used to say Comfort profiles 1 before i updated the files?
Could we also get the name infintude in the tab instead of the IP (sorry me being anal - u can ignore :-) )

<img width="1285" alt="2016-02-02 2" src="https://cloud.githubusercontent.com/assets/11369180/12771365/a54e735a-c9dd-11e5-8132-138f285861de.png">

**Comment by nebulous** [comment]
I unfortunately don't have multiple zones so it's hard for me to test functionality/changes. Can you send me your output of

**Comment by scyto** [comment]
[xmlfiles.zip](https://github.com/nebulous/infinitude/files/118521/xmlfiles.zip)
hope that helps.

**Comment by nebulous** [comment]
Thanks for the config files. They made testing substantially easier. Title should now be "Infinitude" Hold timers and modes should now be hidden unless hold is enabled for the zone. I'm hoping that will address the hold time artifacts you were seeing, but feel free to reopen this issue with more details if not.
