### ISSUE TITLE
Infinitude API Call to Change Climate Mode?

### ISSUE THREAD

**Issue by swerb73** [nebulous/infinitude#90]
Hello, I'm assuming this exists since you can use the Infinitude HTML page(s) (Comfort Porfile) but can't find the documentation. Is there an API call to move from Fan Only to Heat to Cool, etc?

**Comment by nebulous** [comment]
POST to /api/config passing `mode=fanonly` (or heat/cool/auto)

**Comment by swerb73** [comment]
That did it, thank you!

**Comment by metaton8086** [comment]
Hummm...if I read this right...I should be able to change the comfort mode by submitting the following URL request http://<ip>:<port>/api/config/mode=cool (or heat/cool/off/fanonly).  However, this does not seem to work -- perhaps I am misunderstand the API usage.

**Comment by metaton8086** [comment]
> Hummm...if I read this right...I should be able to change the comfort mode by submitting the following URL request http://ip:port/api/config/mode=cool (or heat/cool/off/fanonly). However, this does not seem to work -- perhaps I am misunderstand the API usage.

...NVM...seems I needed a "?" mark, such as http://ip:port/api/config/?mode=cool.
