### ISSUE TITLE
Multiple Carrier Touch Thermostats

### ISSUE THREAD

**Issue by xeroiv** [nebulous/infinitude#94]
Multiple carrier touch thermostats pointing at the same Infinitude instance do not seem to produce desirable results.  Is there a setup step that I am missing by following the raspberry pi setup on the wiki?

**Comment by nebulous** [comment]
Infinitude mimics the Carrier API which only supports single-thermostat calls. You can run multiple instances of Infinitude on different ports, however. Kludgey, but the whole mess is kludgey. 😐

**Comment by xeroiv** [comment]
I setup two services Infinitude and Inifitude2.  The only thing that differed between the two was the port number.  However the data on the dashboard is only for the first thermostat.  There something else in the config that I am missing or should I just run it as a separate container from the first?

**Comment by 7ooL** [comment]
I run two instance in a single slim vm. I simply copied the cloned git repository and have it configured for different ports. I think I made two services. There are two web instances running. I have written a python api that I use to change the configurations if both web services.

**Comment by 7ooL** [comment]
Oh on the two thermostats I configured each to point to one of my running instances. Everything is working as one would.

**Comment by nebulous** [comment]
You'll have to also ensure that they have different storage folders. Either via brute force, having two separate copies of Infinitude each with its own state folder, or by specifying a different `root_dir`in the config

**Comment by xeroiv** [comment]
Ahh... that was  the key.  I just copied the infinitude folder and pointed the new service at the second folder.  Works like a charm.
