### ISSUE TITLE
Lots of empty "0x*" files in state folder

### ISSUE THREAD

**Issue by zraken** [nebulous/infinitude#95]
I noticed that there are about 20 empty files created every minute, these files start with "0x" in their names. I'm basically running with the files and configuration as downloaded from github. The service itself is working fine for my thermostat just that these files are cluttering up the state folder. Is there something I can do to disable creation of these empty files?

**Comment by nebulous** [comment]
This isn't something I've observed. Could you pull the latest version (or Docker image) and see if anything changes? If it's still spewing junk we can try to get to the bottom of what's different in your system.
