### ISSUE TITLE
Devices API call is empty

### ISSUE THREAD

**Issue by cgibsonwellogic** [nebulous/infinitude#96]
Installed web append it appears to be running fine. I can see temp set points, humidity, comfort profiles, etc. However, the /api/devices API call is returning nothing:

{"data":{},"status":"success"}

Should I not see something here?

**Comment by nebulous** [comment]
Was there some documentation which pointed you to use `/api/devices`? Infinitude doesn't implement that endpoint, though due to some wildcards in routing, it does respond to it which can be a bit confusing. `GET /api/somethingblahblah` will return the same empty object.
